#
# NAME
#	  $RCSfile: Makefile,v $
# DESCRIPTION
#	  [given below in javadoc format]
# DELTA
#	  $Revision: 1.9 $
# CREATED
#	  $Date: 2002/10/15 12:59:32 $
# COPYRIGHT
#	  Westhawk Ltd
# TO DO
#

DISTRIBDIR=$(TOPDISTRIBDIR)/uk/co/westhawk/snmp/util

SRC=\
	SnmpUtilities.java 

TOJAR=\
	$(OBJ) 

TOORACLEJAR=$(TOJAR)

TOZIP= \
	$(SRC) \
	Makefile

include ../../../../../Makefile.general

