#
# NAME
#      $RCSfile: Makefile,v $
# DESCRIPTION
#      [given below in javadoc format]
# DELTA
#      $Revision: 1.1 $
# CREATED
#      $Date: 2002/10/15 13:37:01 $
# COPYRIGHT
#      Westhawk Ltd
# TO DO
#

DISTRIBDIR=$(TOPDISTRIBDIR)/uk/co/westhawk/nothread

SRC=

HTML= \
	notes.html

TOJAR= 

TOORACLEJAR=$(TOJAR)

TOZIP= \
	$(HTML) \
	Makefile


DIRS=\
	oscar \
	trap \

JARDIRS=\
	$(DIRS) 

ZIPDIRS=\
	$(DIRS)

ORACLEJARDIRS=trap

include ../../../../Makefile.general

