
(object Petal
    version    	47
    _written   	"Rose 8.0.0303.1400"
    charSet    	0)

(object SubSystem "nbapi"
    is_unit    	TRUE
    is_loaded  	TRUE
    quid       	"3F0C2947024A"
    physical_models 	(list unit_reference_list
	(object module "MessageHandler" "NotAModuleType" "NotAModulePart"
	    quid       	"3F54E814012E"
	    stereotype 	""
	    language   	"Java"))
    physical_presentations 	(list unit_reference_list))
