
(object Petal
    version    	47
    _written   	"Rose 8.0.0303.1400"
    charSet    	0)

(object SubSystem "cisco"
    is_unit    	TRUE
    is_loaded  	TRUE
    quid       	"3F0C28FC0197"
    physical_models 	(list unit_reference_list
	(object SubSystem "eManager"
	    is_unit    	TRUE
	    is_loaded  	FALSE
	    file_name  	"$CURDIR\\com_cisco_eManager.sub"
	    quid       	"3F0C290200EB"))
    physical_presentations 	(list unit_reference_list))
