
(object Petal
    version    	47
    _written   	"Rational Rose 2003.06.00"
    charSet    	0)

(object SubSystem "nio"
    is_unit    	TRUE
    is_loaded  	TRUE
    quid       	"3E400BC40010"
    visible_modules 	(list dependency_list
	(object Module_Visibility_Relationship
	    quid       	"3E400BC600B3"
	    supplier   	"Component View::sun::misc"
	    quidu      	"3E400BBB014E"
	    supplier_is_subsystem 	TRUE)
	(object Module_Visibility_Relationship
	    quid       	"3E400DF4000C"
	    supplier   	"Component View::java::lang"
	    quidu      	"3E400BBB015B"
	    supplier_is_subsystem 	TRUE))
    physical_models 	(list unit_reference_list
	(object module "Bits" "NotAModuleType" "NotAModulePart"
	    attributes 	(list Attribute_Set
		(object Attribute
		    tool       	"Java"
		    name       	"FileName"
		    value      	"java\\nio\\Bits.class")
		(object Attribute
		    tool       	"Java"
		    name       	"RootPath"
		    value      	"")
		(object Attribute
		    tool       	"Java"
		    name       	"CmIdentification"
		    value      	(value Text ""))
		(object Attribute
		    tool       	"Java"
		    name       	"CopyrightNotice"
		    value      	(value Text "")))
	    quid       	"3E400BC40011"
	    stereotype 	""
	    visible_modules 	(list dependency_list
		(object Module_Visibility_Relationship
		    quid       	"3E400BC600B4"
		    supplier   	"Unsafe"
		    quidu      	"3E400BC4001F"
		    supplier_is_spec 	TRUE)
		(object Module_Visibility_Relationship
		    quid       	"3E400BC600B5"
		    supplier   	"Component View::java::nio::ByteOrder"
		    quidu      	"3E400BC4003A"
		    supplier_is_spec 	TRUE))
	    language   	"Java")
	(object module "ByteOrder" "NotAModuleType" "NotAModulePart"
	    attributes 	(list Attribute_Set
		(object Attribute
		    tool       	"Java"
		    name       	"FileName"
		    value      	"java\\nio\\ByteOrder.class")
		(object Attribute
		    tool       	"Java"
		    name       	"RootPath"
		    value      	"")
		(object Attribute
		    tool       	"Java"
		    name       	"CmIdentification"
		    value      	(value Text ""))
		(object Attribute
		    tool       	"Java"
		    name       	"CopyrightNotice"
		    value      	(value Text "")))
	    quid       	"3E400BC4003A"
	    stereotype 	""
	    language   	"Java")
	(object module "ByteBuffer" "NotAModuleType" "NotAModulePart"
	    attributes 	(list Attribute_Set
		(object Attribute
		    tool       	"Java"
		    name       	"FileName"
		    value      	"java\\nio\\ByteBuffer.class")
		(object Attribute
		    tool       	"Java"
		    name       	"RootPath"
		    value      	"")
		(object Attribute
		    tool       	"Java"
		    name       	"CmIdentification"
		    value      	(value Text ""))
		(object Attribute
		    tool       	"Java"
		    name       	"CopyrightNotice"
		    value      	(value Text "")))
	    quid       	"3E400BC40092"
	    stereotype 	""
	    language   	"Java")
	(object module "MappedByteBuffer" "NotAModuleType" "NotAModulePart"
	    attributes 	(list Attribute_Set
		(object Attribute
		    tool       	"Java"
		    name       	"FileName"
		    value      	"java\\nio\\MappedByteBuffer.class")
		(object Attribute
		    tool       	"Java"
		    name       	"RootPath"
		    value      	"")
		(object Attribute
		    tool       	"Java"
		    name       	"CmIdentification"
		    value      	(value Text ""))
		(object Attribute
		    tool       	"Java"
		    name       	"CopyrightNotice"
		    value      	(value Text "")))
	    quid       	"3E400BE5009A"
	    stereotype 	""
	    language   	"Java")
	(object module "Buffer" "NotAModuleType" "NotAModulePart"
	    attributes 	(list Attribute_Set
		(object Attribute
		    tool       	"Java"
		    name       	"FileName"
		    value      	"java\\nio\\Buffer.class")
		(object Attribute
		    tool       	"Java"
		    name       	"RootPath"
		    value      	"")
		(object Attribute
		    tool       	"Java"
		    name       	"CmIdentification"
		    value      	(value Text ""))
		(object Attribute
		    tool       	"Java"
		    name       	"CopyrightNotice"
		    value      	(value Text "")))
	    quid       	"3E400BE60344"
	    stereotype 	""
	    language   	"Java")
	(object module "IntBuffer" "NotAModuleType" "NotAModulePart"
	    attributes 	(list Attribute_Set
		(object Attribute
		    tool       	"Java"
		    name       	"FileName"
		    value      	"java\\nio\\IntBuffer.class")
		(object Attribute
		    tool       	"Java"
		    name       	"RootPath"
		    value      	"")
		(object Attribute
		    tool       	"Java"
		    name       	"CmIdentification"
		    value      	(value Text ""))
		(object Attribute
		    tool       	"Java"
		    name       	"CopyrightNotice"
		    value      	(value Text "")))
	    quid       	"3E400C21012C"
	    stereotype 	""
	    language   	"Java")
	(object module "LongBuffer" "NotAModuleType" "NotAModulePart"
	    attributes 	(list Attribute_Set
		(object Attribute
		    tool       	"Java"
		    name       	"FileName"
		    value      	"java\\nio\\LongBuffer.class")
		(object Attribute
		    tool       	"Java"
		    name       	"RootPath"
		    value      	"")
		(object Attribute
		    tool       	"Java"
		    name       	"CmIdentification"
		    value      	(value Text ""))
		(object Attribute
		    tool       	"Java"
		    name       	"CopyrightNotice"
		    value      	(value Text "")))
	    quid       	"3E400C560273"
	    stereotype 	""
	    language   	"Java")
	(object module "CharBuffer" "NotAModuleType" "NotAModulePart"
	    attributes 	(list Attribute_Set
		(object Attribute
		    tool       	"Java"
		    name       	"FileName"
		    value      	"java\\nio\\CharBuffer.class")
		(object Attribute
		    tool       	"Java"
		    name       	"RootPath"
		    value      	"")
		(object Attribute
		    tool       	"Java"
		    name       	"CmIdentification"
		    value      	(value Text ""))
		(object Attribute
		    tool       	"Java"
		    name       	"CopyrightNotice"
		    value      	(value Text "")))
	    quid       	"3E400C5B037E"
	    stereotype 	""
	    language   	"Java")
	(object module "ShortBuffer" "NotAModuleType" "NotAModulePart"
	    attributes 	(list Attribute_Set
		(object Attribute
		    tool       	"Java"
		    name       	"FileName"
		    value      	"java\\nio\\ShortBuffer.class")
		(object Attribute
		    tool       	"Java"
		    name       	"RootPath"
		    value      	"")
		(object Attribute
		    tool       	"Java"
		    name       	"CmIdentification"
		    value      	(value Text ""))
		(object Attribute
		    tool       	"Java"
		    name       	"CopyrightNotice"
		    value      	(value Text "")))
	    quid       	"3E400C6902D5"
	    stereotype 	""
	    language   	"Java")
	(object module "FloatBuffer" "NotAModuleType" "NotAModulePart"
	    attributes 	(list Attribute_Set
		(object Attribute
		    tool       	"Java"
		    name       	"FileName"
		    value      	"java\\nio\\FloatBuffer.class")
		(object Attribute
		    tool       	"Java"
		    name       	"RootPath"
		    value      	"")
		(object Attribute
		    tool       	"Java"
		    name       	"CmIdentification"
		    value      	(value Text ""))
		(object Attribute
		    tool       	"Java"
		    name       	"CopyrightNotice"
		    value      	(value Text "")))
	    quid       	"3E400C69037F"
	    stereotype 	""
	    language   	"Java")
	(object module "DoubleBuffer" "NotAModuleType" "NotAModulePart"
	    attributes 	(list Attribute_Set
		(object Attribute
		    tool       	"Java"
		    name       	"FileName"
		    value      	"java\\nio\\DoubleBuffer.class")
		(object Attribute
		    tool       	"Java"
		    name       	"RootPath"
		    value      	"")
		(object Attribute
		    tool       	"Java"
		    name       	"CmIdentification"
		    value      	(value Text ""))
		(object Attribute
		    tool       	"Java"
		    name       	"CopyrightNotice"
		    value      	(value Text "")))
	    quid       	"3E400C6903BB"
	    stereotype 	""
	    language   	"Java")
	(object module "HeapIntBuffer" "NotAModuleType" "NotAModulePart"
	    attributes 	(list Attribute_Set
		(object Attribute
		    tool       	"Java"
		    name       	"FileName"
		    value      	"java\\nio\\HeapIntBuffer.class")
		(object Attribute
		    tool       	"Java"
		    name       	"RootPath"
		    value      	"")
		(object Attribute
		    tool       	"Java"
		    name       	"CmIdentification"
		    value      	(value Text ""))
		(object Attribute
		    tool       	"Java"
		    name       	"CopyrightNotice"
		    value      	(value Text "")))
	    quid       	"3E400D1D0138"
	    stereotype 	""
	    language   	"Java")
	(object module "HeapIntBufferR" "NotAModuleType" "NotAModulePart"
	    attributes 	(list Attribute_Set
		(object Attribute
		    tool       	"Java"
		    name       	"FileName"
		    value      	"java\\nio\\HeapIntBufferR.class")
		(object Attribute
		    tool       	"Java"
		    name       	"RootPath"
		    value      	"")
		(object Attribute
		    tool       	"Java"
		    name       	"CmIdentification"
		    value      	(value Text ""))
		(object Attribute
		    tool       	"Java"
		    name       	"CopyrightNotice"
		    value      	(value Text "")))
	    quid       	"3E400D6601C0"
	    stereotype 	""
	    language   	"Java")
	(object module "HeapByteBuffer" "NotAModuleType" "NotAModulePart"
	    attributes 	(list Attribute_Set
		(object Attribute
		    tool       	"Java"
		    name       	"FileName"
		    value      	"java\\nio\\HeapByteBuffer.class")
		(object Attribute
		    tool       	"Java"
		    name       	"RootPath"
		    value      	"")
		(object Attribute
		    tool       	"Java"
		    name       	"CmIdentification"
		    value      	(value Text ""))
		(object Attribute
		    tool       	"Java"
		    name       	"CopyrightNotice"
		    value      	(value Text "")))
	    quid       	"3E400D6A03C4"
	    stereotype 	""
	    language   	"Java")
	(object module "HeapCharBuffer" "NotAModuleType" "NotAModulePart"
	    attributes 	(list Attribute_Set
		(object Attribute
		    tool       	"Java"
		    name       	"FileName"
		    value      	"java\\nio\\HeapCharBuffer.class")
		(object Attribute
		    tool       	"Java"
		    name       	"RootPath"
		    value      	"")
		(object Attribute
		    tool       	"Java"
		    name       	"CmIdentification"
		    value      	(value Text ""))
		(object Attribute
		    tool       	"Java"
		    name       	"CopyrightNotice"
		    value      	(value Text "")))
	    quid       	"3E400D7B01AC"
	    stereotype 	""
	    language   	"Java")
	(object module "HeapLongBuffer" "NotAModuleType" "NotAModulePart"
	    attributes 	(list Attribute_Set
		(object Attribute
		    tool       	"Java"
		    name       	"FileName"
		    value      	"java\\nio\\HeapLongBuffer.class")
		(object Attribute
		    tool       	"Java"
		    name       	"RootPath"
		    value      	"")
		(object Attribute
		    tool       	"Java"
		    name       	"CmIdentification"
		    value      	(value Text ""))
		(object Attribute
		    tool       	"Java"
		    name       	"CopyrightNotice"
		    value      	(value Text "")))
	    quid       	"3E400D800086"
	    stereotype 	""
	    language   	"Java")
	(object module "HeapFloatBuffer" "NotAModuleType" "NotAModulePart"
	    attributes 	(list Attribute_Set
		(object Attribute
		    tool       	"Java"
		    name       	"FileName"
		    value      	"java\\nio\\HeapFloatBuffer.class")
		(object Attribute
		    tool       	"Java"
		    name       	"RootPath"
		    value      	"")
		(object Attribute
		    tool       	"Java"
		    name       	"CmIdentification"
		    value      	(value Text ""))
		(object Attribute
		    tool       	"Java"
		    name       	"CopyrightNotice"
		    value      	(value Text "")))
	    quid       	"3E400DE0014D"
	    stereotype 	""
	    language   	"Java")
	(object module "HeapByteBufferR" "NotAModuleType" "NotAModulePart"
	    attributes 	(list Attribute_Set
		(object Attribute
		    tool       	"Java"
		    name       	"FileName"
		    value      	"java\\nio\\HeapByteBufferR.class")
		(object Attribute
		    tool       	"Java"
		    name       	"RootPath"
		    value      	"")
		(object Attribute
		    tool       	"Java"
		    name       	"CmIdentification"
		    value      	(value Text ""))
		(object Attribute
		    tool       	"Java"
		    name       	"CopyrightNotice"
		    value      	(value Text "")))
	    quid       	"3E400DEF0176"
	    stereotype 	""
	    language   	"Java")
	(object module "HeapLongBufferR" "NotAModuleType" "NotAModulePart"
	    attributes 	(list Attribute_Set
		(object Attribute
		    tool       	"Java"
		    name       	"FileName"
		    value      	"java\\nio\\HeapLongBufferR.class")
		(object Attribute
		    tool       	"Java"
		    name       	"RootPath"
		    value      	"")
		(object Attribute
		    tool       	"Java"
		    name       	"CmIdentification"
		    value      	(value Text ""))
		(object Attribute
		    tool       	"Java"
		    name       	"CopyrightNotice"
		    value      	(value Text "")))
	    quid       	"3E400DF00268"
	    stereotype 	""
	    language   	"Java")
	(object module "HeapCharBufferR" "NotAModuleType" "NotAModulePart"
	    attributes 	(list Attribute_Set
		(object Attribute
		    tool       	"Java"
		    name       	"FileName"
		    value      	"java\\nio\\HeapCharBufferR.class")
		(object Attribute
		    tool       	"Java"
		    name       	"RootPath"
		    value      	"")
		(object Attribute
		    tool       	"Java"
		    name       	"CmIdentification"
		    value      	(value Text ""))
		(object Attribute
		    tool       	"Java"
		    name       	"CopyrightNotice"
		    value      	(value Text "")))
	    quid       	"3E400DF00377"
	    stereotype 	""
	    language   	"Java")
	(object module "HeapShortBuffer" "NotAModuleType" "NotAModulePart"
	    attributes 	(list Attribute_Set
		(object Attribute
		    tool       	"Java"
		    name       	"FileName"
		    value      	"java\\nio\\HeapShortBuffer.class")
		(object Attribute
		    tool       	"Java"
		    name       	"RootPath"
		    value      	"")
		(object Attribute
		    tool       	"Java"
		    name       	"CmIdentification"
		    value      	(value Text ""))
		(object Attribute
		    tool       	"Java"
		    name       	"CopyrightNotice"
		    value      	(value Text "")))
	    quid       	"3E400DF2010D"
	    stereotype 	""
	    language   	"Java")
	(object module "DirectIntBufferU" "NotAModuleType" "NotAModulePart"
	    attributes 	(list Attribute_Set
		(object Attribute
		    tool       	"Java"
		    name       	"FileName"
		    value      	"java\\nio\\DirectIntBufferU.class")
		(object Attribute
		    tool       	"Java"
		    name       	"RootPath"
		    value      	"")
		(object Attribute
		    tool       	"Java"
		    name       	"CmIdentification"
		    value      	(value Text ""))
		(object Attribute
		    tool       	"Java"
		    name       	"CopyrightNotice"
		    value      	(value Text "")))
	    quid       	"3E400DF302BD"
	    stereotype 	""
	    visible_modules 	(list dependency_list
		(object Module_Visibility_Relationship
		    quid       	"3E400DF4000B"
		    supplier   	"Unsafe"
		    quidu      	"3E400BC4001F"
		    supplier_is_spec 	TRUE)
		(object Module_Visibility_Relationship
		    quid       	"3E400DF40015"
		    supplier   	"Component View::java::lang::Class"
		    quidu      	"3E400BBB0176"
		    supplier_is_spec 	TRUE))
	    language   	"Java")
	(object module "DirectByteBuffer" "NotAModuleType" "NotAModulePart"
	    attributes 	(list Attribute_Set
		(object Attribute
		    tool       	"Java"
		    name       	"FileName"
		    value      	"java\\nio\\DirectByteBuffer.class")
		(object Attribute
		    tool       	"Java"
		    name       	"RootPath"
		    value      	"")
		(object Attribute
		    tool       	"Java"
		    name       	"CmIdentification"
		    value      	(value Text ""))
		(object Attribute
		    tool       	"Java"
		    name       	"CopyrightNotice"
		    value      	(value Text "")))
	    quid       	"3E400DF3032B"
	    stereotype 	""
	    visible_modules 	(list dependency_list
		(object Module_Visibility_Relationship
		    quid       	"3E400E4F0297"
		    supplier   	"Unsafe"
		    quidu      	"3E400BC4001F"
		    supplier_is_spec 	TRUE)
		(object Module_Visibility_Relationship
		    quid       	"3E400E4F02A1"
		    supplier   	"Component View::java::lang::Class"
		    quidu      	"3E400BBB0176"
		    supplier_is_spec 	TRUE))
	    language   	"Java")
	(object module "HeapDoubleBuffer" "NotAModuleType" "NotAModulePart"
	    attributes 	(list Attribute_Set
		(object Attribute
		    tool       	"Java"
		    name       	"FileName"
		    value      	"java\\nio\\HeapDoubleBuffer.class")
		(object Attribute
		    tool       	"Java"
		    name       	"RootPath"
		    value      	"")
		(object Attribute
		    tool       	"Java"
		    name       	"CmIdentification"
		    value      	(value Text ""))
		(object Attribute
		    tool       	"Java"
		    name       	"CopyrightNotice"
		    value      	(value Text "")))
	    quid       	"3E400DF5034C"
	    stereotype 	""
	    language   	"Java")
	(object module "HeapShortBufferR" "NotAModuleType" "NotAModulePart"
	    attributes 	(list Attribute_Set
		(object Attribute
		    tool       	"Java"
		    name       	"FileName"
		    value      	"java\\nio\\HeapShortBufferR.class")
		(object Attribute
		    tool       	"Java"
		    name       	"RootPath"
		    value      	"")
		(object Attribute
		    tool       	"Java"
		    name       	"CmIdentification"
		    value      	(value Text ""))
		(object Attribute
		    tool       	"Java"
		    name       	"CopyrightNotice"
		    value      	(value Text "")))
	    quid       	"3E400DF60144"
	    stereotype 	""
	    language   	"Java")
	(object module "StringCharBuffer" "NotAModuleType" "NotAModulePart"
	    attributes 	(list Attribute_Set
		(object Attribute
		    tool       	"Java"
		    name       	"FileName"
		    value      	"java\\nio\\StringCharBuffer.class")
		(object Attribute
		    tool       	"Java"
		    name       	"RootPath"
		    value      	"")
		(object Attribute
		    tool       	"Java"
		    name       	"CmIdentification"
		    value      	(value Text ""))
		(object Attribute
		    tool       	"Java"
		    name       	"CopyrightNotice"
		    value      	(value Text "")))
	    quid       	"3E400DFF03BE"
	    stereotype 	""
	    visible_modules 	(list dependency_list
		(object Module_Visibility_Relationship
		    quid       	"3E400E000095"
		    supplier   	"Component View::java::lang::CharSequence"
		    quidu      	"3E400BED02AF"
		    supplier_is_spec 	TRUE))
	    language   	"Java")
	(object module "HeapFloatBufferR" "NotAModuleType" "NotAModulePart"
	    attributes 	(list Attribute_Set
		(object Attribute
		    tool       	"Java"
		    name       	"FileName"
		    value      	"java\\nio\\HeapFloatBufferR.class")
		(object Attribute
		    tool       	"Java"
		    name       	"RootPath"
		    value      	"")
		(object Attribute
		    tool       	"Java"
		    name       	"CmIdentification"
		    value      	(value Text ""))
		(object Attribute
		    tool       	"Java"
		    name       	"CopyrightNotice"
		    value      	(value Text "")))
	    quid       	"3E400E080096"
	    stereotype 	""
	    language   	"Java")
	(object module "DirectIntBufferS" "NotAModuleType" "NotAModulePart"
	    attributes 	(list Attribute_Set
		(object Attribute
		    tool       	"Java"
		    name       	"FileName"
		    value      	"java\\nio\\DirectIntBufferS.class")
		(object Attribute
		    tool       	"Java"
		    name       	"RootPath"
		    value      	"")
		(object Attribute
		    tool       	"Java"
		    name       	"CmIdentification"
		    value      	(value Text ""))
		(object Attribute
		    tool       	"Java"
		    name       	"CopyrightNotice"
		    value      	(value Text "")))
	    quid       	"3E400E2B00B4"
	    stereotype 	""
	    visible_modules 	(list dependency_list
		(object Module_Visibility_Relationship
		    quid       	"3E400E2B01E1"
		    supplier   	"Unsafe"
		    quidu      	"3E400BC4001F"
		    supplier_is_spec 	TRUE)
		(object Module_Visibility_Relationship
		    quid       	"3E400E2B01EB"
		    supplier   	"Component View::java::lang::Class"
		    quidu      	"3E400BBB0176"
		    supplier_is_spec 	TRUE))
	    language   	"Java")
	(object module "DirectIntBufferRS" "NotAModuleType" "NotAModulePart"
	    attributes 	(list Attribute_Set
		(object Attribute
		    tool       	"Java"
		    name       	"FileName"
		    value      	"java\\nio\\DirectIntBufferRS.class")
		(object Attribute
		    tool       	"Java"
		    name       	"RootPath"
		    value      	"")
		(object Attribute
		    tool       	"Java"
		    name       	"CmIdentification"
		    value      	(value Text ""))
		(object Attribute
		    tool       	"Java"
		    name       	"CopyrightNotice"
		    value      	(value Text "")))
	    quid       	"3E400E9B00D4"
	    stereotype 	""
	    visible_modules 	(list dependency_list
		(object Module_Visibility_Relationship
		    quid       	"3E400E9B01CE"
		    supplier   	"Component View::java::lang::Class"
		    quidu      	"3E400BBB0176"
		    supplier_is_spec 	TRUE))
	    language   	"Java")
	(object module "DirectByteBufferR" "NotAModuleType" "NotAModulePart"
	    attributes 	(list Attribute_Set
		(object Attribute
		    tool       	"Java"
		    name       	"FileName"
		    value      	"java\\nio\\DirectByteBufferR.class")
		(object Attribute
		    tool       	"Java"
		    name       	"RootPath"
		    value      	"")
		(object Attribute
		    tool       	"Java"
		    name       	"CmIdentification"
		    value      	(value Text ""))
		(object Attribute
		    tool       	"Java"
		    name       	"CopyrightNotice"
		    value      	(value Text "")))
	    quid       	"3E400E9B0124"
	    stereotype 	""
	    visible_modules 	(list dependency_list
		(object Module_Visibility_Relationship
		    quid       	"3E400EA300A3"
		    supplier   	"Component View::java::lang::Class"
		    quidu      	"3E400BBB0176"
		    supplier_is_spec 	TRUE))
	    language   	"Java")
	(object module "DirectLongBufferU" "NotAModuleType" "NotAModulePart"
	    attributes 	(list Attribute_Set
		(object Attribute
		    tool       	"Java"
		    name       	"FileName"
		    value      	"java\\nio\\DirectLongBufferU.class")
		(object Attribute
		    tool       	"Java"
		    name       	"RootPath"
		    value      	"")
		(object Attribute
		    tool       	"Java"
		    name       	"CmIdentification"
		    value      	(value Text ""))
		(object Attribute
		    tool       	"Java"
		    name       	"CopyrightNotice"
		    value      	(value Text "")))
	    quid       	"3E400EA1033F"
	    stereotype 	""
	    visible_modules 	(list dependency_list
		(object Module_Visibility_Relationship
		    quid       	"3E400EA200A2"
		    supplier   	"Unsafe"
		    quidu      	"3E400BC4001F"
		    supplier_is_spec 	TRUE)
		(object Module_Visibility_Relationship
		    quid       	"3E400EA200AC"
		    supplier   	"Component View::java::lang::Class"
		    quidu      	"3E400BBB0176"
		    supplier_is_spec 	TRUE))
	    language   	"Java")
	(object module "DirectLongBufferS" "NotAModuleType" "NotAModulePart"
	    attributes 	(list Attribute_Set
		(object Attribute
		    tool       	"Java"
		    name       	"FileName"
		    value      	"java\\nio\\DirectLongBufferS.class")
		(object Attribute
		    tool       	"Java"
		    name       	"RootPath"
		    value      	"")
		(object Attribute
		    tool       	"Java"
		    name       	"CmIdentification"
		    value      	(value Text ""))
		(object Attribute
		    tool       	"Java"
		    name       	"CopyrightNotice"
		    value      	(value Text "")))
	    quid       	"3E400EA301ED"
	    stereotype 	""
	    visible_modules 	(list dependency_list
		(object Module_Visibility_Relationship
		    quid       	"3E400EA30338"
		    supplier   	"Unsafe"
		    quidu      	"3E400BC4001F"
		    supplier_is_spec 	TRUE)
		(object Module_Visibility_Relationship
		    quid       	"3E400EA30342"
		    supplier   	"Component View::java::lang::Class"
		    quidu      	"3E400BBB0176"
		    supplier_is_spec 	TRUE))
	    language   	"Java")
	(object module "DirectCharBufferU" "NotAModuleType" "NotAModulePart"
	    attributes 	(list Attribute_Set
		(object Attribute
		    tool       	"Java"
		    name       	"FileName"
		    value      	"java\\nio\\DirectCharBufferU.class")
		(object Attribute
		    tool       	"Java"
		    name       	"RootPath"
		    value      	"")
		(object Attribute
		    tool       	"Java"
		    name       	"CmIdentification"
		    value      	(value Text ""))
		(object Attribute
		    tool       	"Java"
		    name       	"CopyrightNotice"
		    value      	(value Text "")))
	    quid       	"3E400EA400A4"
	    stereotype 	""
	    visible_modules 	(list dependency_list
		(object Module_Visibility_Relationship
		    quid       	"3E400EA4020D"
		    supplier   	"Unsafe"
		    quidu      	"3E400BC4001F"
		    supplier_is_spec 	TRUE)
		(object Module_Visibility_Relationship
		    quid       	"3E400EA40217"
		    supplier   	"Component View::java::lang::Class"
		    quidu      	"3E400BBB0176"
		    supplier_is_spec 	TRUE))
	    language   	"Java")
	(object module "DirectCharBufferS" "NotAModuleType" "NotAModulePart"
	    attributes 	(list Attribute_Set
		(object Attribute
		    tool       	"Java"
		    name       	"FileName"
		    value      	"java\\nio\\DirectCharBufferS.class")
		(object Attribute
		    tool       	"Java"
		    name       	"RootPath"
		    value      	"")
		(object Attribute
		    tool       	"Java"
		    name       	"CmIdentification"
		    value      	(value Text ""))
		(object Attribute
		    tool       	"Java"
		    name       	"CopyrightNotice"
		    value      	(value Text "")))
	    quid       	"3E400EA4036B"
	    stereotype 	""
	    visible_modules 	(list dependency_list
		(object Module_Visibility_Relationship
		    quid       	"3E400EA500E2"
		    supplier   	"Unsafe"
		    quidu      	"3E400BC4001F"
		    supplier_is_spec 	TRUE)
		(object Module_Visibility_Relationship
		    quid       	"3E400EA500EC"
		    supplier   	"Component View::java::lang::Class"
		    quidu      	"3E400BBB0176"
		    supplier_is_spec 	TRUE))
	    language   	"Java")
	(object module "HeapDoubleBufferR" "NotAModuleType" "NotAModulePart"
	    attributes 	(list Attribute_Set
		(object Attribute
		    tool       	"Java"
		    name       	"FileName"
		    value      	"java\\nio\\HeapDoubleBufferR.class")
		(object Attribute
		    tool       	"Java"
		    name       	"RootPath"
		    value      	"")
		(object Attribute
		    tool       	"Java"
		    name       	"CmIdentification"
		    value      	(value Text ""))
		(object Attribute
		    tool       	"Java"
		    name       	"CopyrightNotice"
		    value      	(value Text "")))
	    quid       	"3E400EA7024D"
	    stereotype 	""
	    language   	"Java")
	(object module "DirectIntBufferRU" "NotAModuleType" "NotAModulePart"
	    attributes 	(list Attribute_Set
		(object Attribute
		    tool       	"Java"
		    name       	"FileName"
		    value      	"java\\nio\\DirectIntBufferRU.class")
		(object Attribute
		    tool       	"Java"
		    name       	"RootPath"
		    value      	"")
		(object Attribute
		    tool       	"Java"
		    name       	"CmIdentification"
		    value      	(value Text ""))
		(object Attribute
		    tool       	"Java"
		    name       	"CopyrightNotice"
		    value      	(value Text "")))
	    quid       	"3E400EAA014D"
	    stereotype 	""
	    visible_modules 	(list dependency_list
		(object Module_Visibility_Relationship
		    quid       	"3E400EAA0248"
		    supplier   	"Component View::java::lang::Class"
		    quidu      	"3E400BBB0176"
		    supplier_is_spec 	TRUE))
	    language   	"Java")
	(object module "DirectFloatBufferS" "NotAModuleType" "NotAModulePart"
	    attributes 	(list Attribute_Set
		(object Attribute
		    tool       	"Java"
		    name       	"FileName"
		    value      	"java\\nio\\DirectFloatBufferS.class")
		(object Attribute
		    tool       	"Java"
		    name       	"RootPath"
		    value      	"")
		(object Attribute
		    tool       	"Java"
		    name       	"CmIdentification"
		    value      	(value Text ""))
		(object Attribute
		    tool       	"Java"
		    name       	"CopyrightNotice"
		    value      	(value Text "")))
	    quid       	"3E400F1F00DD"
	    stereotype 	""
	    visible_modules 	(list dependency_list
		(object Module_Visibility_Relationship
		    quid       	"3E400F1F023C"
		    supplier   	"Unsafe"
		    quidu      	"3E400BC4001F"
		    supplier_is_spec 	TRUE)
		(object Module_Visibility_Relationship
		    quid       	"3E400F1F0246"
		    supplier   	"Component View::java::lang::Class"
		    quidu      	"3E400BBB0176"
		    supplier_is_spec 	TRUE))
	    language   	"Java")
	(object module "DirectCharBufferRS" "NotAModuleType" "NotAModulePart"
	    attributes 	(list Attribute_Set
		(object Attribute
		    tool       	"Java"
		    name       	"FileName"
		    value      	"java\\nio\\DirectCharBufferRS.class")
		(object Attribute
		    tool       	"Java"
		    name       	"RootPath"
		    value      	"")
		(object Attribute
		    tool       	"Java"
		    name       	"CmIdentification"
		    value      	(value Text ""))
		(object Attribute
		    tool       	"Java"
		    name       	"CopyrightNotice"
		    value      	(value Text "")))
	    quid       	"3E400F210194"
	    stereotype 	""
	    visible_modules 	(list dependency_list
		(object Module_Visibility_Relationship
		    quid       	"3E400F2102B7"
		    supplier   	"Component View::java::lang::Class"
		    quidu      	"3E400BBB0176"
		    supplier_is_spec 	TRUE))
	    language   	"Java")
	(object module "DirectCharBufferRU" "NotAModuleType" "NotAModulePart"
	    attributes 	(list Attribute_Set
		(object Attribute
		    tool       	"Java"
		    name       	"FileName"
		    value      	"java\\nio\\DirectCharBufferRU.class")
		(object Attribute
		    tool       	"Java"
		    name       	"RootPath"
		    value      	"")
		(object Attribute
		    tool       	"Java"
		    name       	"CmIdentification"
		    value      	(value Text ""))
		(object Attribute
		    tool       	"Java"
		    name       	"CopyrightNotice"
		    value      	(value Text "")))
	    quid       	"3E400F2103B1"
	    stereotype 	""
	    visible_modules 	(list dependency_list
		(object Module_Visibility_Relationship
		    quid       	"3E400F2200E2"
		    supplier   	"Component View::java::lang::Class"
		    quidu      	"3E400BBB0176"
		    supplier_is_spec 	TRUE))
	    language   	"Java")
	(object module "DirectFloatBufferU" "NotAModuleType" "NotAModulePart"
	    attributes 	(list Attribute_Set
		(object Attribute
		    tool       	"Java"
		    name       	"FileName"
		    value      	"java\\nio\\DirectFloatBufferU.class")
		(object Attribute
		    tool       	"Java"
		    name       	"RootPath"
		    value      	"")
		(object Attribute
		    tool       	"Java"
		    name       	"CmIdentification"
		    value      	(value Text ""))
		(object Attribute
		    tool       	"Java"
		    name       	"CopyrightNotice"
		    value      	(value Text "")))
	    quid       	"3E400F2501D6"
	    stereotype 	""
	    visible_modules 	(list dependency_list
		(object Module_Visibility_Relationship
		    quid       	"3E400F25032B"
		    supplier   	"Unsafe"
		    quidu      	"3E400BC4001F"
		    supplier_is_spec 	TRUE)
		(object Module_Visibility_Relationship
		    quid       	"3E400F250335"
		    supplier   	"Component View::java::lang::Class"
		    quidu      	"3E400BBB0176"
		    supplier_is_spec 	TRUE))
	    language   	"Java")
	(object module "DirectLongBufferRS" "NotAModuleType" "NotAModulePart"
	    attributes 	(list Attribute_Set
		(object Attribute
		    tool       	"Java"
		    name       	"FileName"
		    value      	"java\\nio\\DirectLongBufferRS.class")
		(object Attribute
		    tool       	"Java"
		    name       	"RootPath"
		    value      	"")
		(object Attribute
		    tool       	"Java"
		    name       	"CmIdentification"
		    value      	(value Text ""))
		(object Attribute
		    tool       	"Java"
		    name       	"CopyrightNotice"
		    value      	(value Text "")))
	    quid       	"3E400F2C033F"
	    stereotype 	""
	    visible_modules 	(list dependency_list
		(object Module_Visibility_Relationship
		    quid       	"3E400F2D005B"
		    supplier   	"Component View::java::lang::Class"
		    quidu      	"3E400BBB0176"
		    supplier_is_spec 	TRUE))
	    language   	"Java")
	(object module "DirectLongBufferRU" "NotAModuleType" "NotAModulePart"
	    attributes 	(list Attribute_Set
		(object Attribute
		    tool       	"Java"
		    name       	"FileName"
		    value      	"java\\nio\\DirectLongBufferRU.class")
		(object Attribute
		    tool       	"Java"
		    name       	"RootPath"
		    value      	"")
		(object Attribute
		    tool       	"Java"
		    name       	"CmIdentification"
		    value      	(value Text ""))
		(object Attribute
		    tool       	"Java"
		    name       	"CopyrightNotice"
		    value      	(value Text "")))
	    quid       	"3E400F2D0156"
	    stereotype 	""
	    visible_modules 	(list dependency_list
		(object Module_Visibility_Relationship
		    quid       	"3E400F2D025A"
		    supplier   	"Component View::java::lang::Class"
		    quidu      	"3E400BBB0176"
		    supplier_is_spec 	TRUE))
	    language   	"Java")
	(object module "DirectShortBufferU" "NotAModuleType" "NotAModulePart"
	    attributes 	(list Attribute_Set
		(object Attribute
		    tool       	"Java"
		    name       	"FileName"
		    value      	"java\\nio\\DirectShortBufferU.class")
		(object Attribute
		    tool       	"Java"
		    name       	"RootPath"
		    value      	"")
		(object Attribute
		    tool       	"Java"
		    name       	"CmIdentification"
		    value      	(value Text ""))
		(object Attribute
		    tool       	"Java"
		    name       	"CopyrightNotice"
		    value      	(value Text "")))
	    quid       	"3E400F2F031B"
	    stereotype 	""
	    visible_modules 	(list dependency_list
		(object Module_Visibility_Relationship
		    quid       	"3E400F300092"
		    supplier   	"Unsafe"
		    quidu      	"3E400BC4001F"
		    supplier_is_spec 	TRUE)
		(object Module_Visibility_Relationship
		    quid       	"3E400F30009C"
		    supplier   	"Component View::java::lang::Class"
		    quidu      	"3E400BBB0176"
		    supplier_is_spec 	TRUE))
	    language   	"Java")
	(object module "DirectShortBufferS" "NotAModuleType" "NotAModulePart"
	    attributes 	(list Attribute_Set
		(object Attribute
		    tool       	"Java"
		    name       	"FileName"
		    value      	"java\\nio\\DirectShortBufferS.class")
		(object Attribute
		    tool       	"Java"
		    name       	"RootPath"
		    value      	"")
		(object Attribute
		    tool       	"Java"
		    name       	"CmIdentification"
		    value      	(value Text ""))
		(object Attribute
		    tool       	"Java"
		    name       	"CopyrightNotice"
		    value      	(value Text "")))
	    quid       	"3E400F31026A"
	    stereotype 	""
	    visible_modules 	(list dependency_list
		(object Module_Visibility_Relationship
		    quid       	"3E400F3103DC"
		    supplier   	"Unsafe"
		    quidu      	"3E400BC4001F"
		    supplier_is_spec 	TRUE)
		(object Module_Visibility_Relationship
		    quid       	"3E400F3103E6"
		    supplier   	"Component View::java::lang::Class"
		    quidu      	"3E400BBB0176"
		    supplier_is_spec 	TRUE))
	    language   	"Java")
	(object module "DirectDoubleBufferS" "NotAModuleType" "NotAModulePart"
	    attributes 	(list Attribute_Set
		(object Attribute
		    tool       	"Java"
		    name       	"FileName"
		    value      	"java\\nio\\DirectDoubleBufferS.class")
		(object Attribute
		    tool       	"Java"
		    name       	"RootPath"
		    value      	"")
		(object Attribute
		    tool       	"Java"
		    name       	"CmIdentification"
		    value      	(value Text ""))
		(object Attribute
		    tool       	"Java"
		    name       	"CopyrightNotice"
		    value      	(value Text "")))
	    quid       	"3E400F7300D4"
	    stereotype 	""
	    visible_modules 	(list dependency_list
		(object Module_Visibility_Relationship
		    quid       	"3E400F73023D"
		    supplier   	"Unsafe"
		    quidu      	"3E400BC4001F"
		    supplier_is_spec 	TRUE)
		(object Module_Visibility_Relationship
		    quid       	"3E400F730247"
		    supplier   	"Component View::java::lang::Class"
		    quidu      	"3E400BBB0176"
		    supplier_is_spec 	TRUE))
	    language   	"Java")
	(object module "DirectDoubleBufferU" "NotAModuleType" "NotAModulePart"
	    attributes 	(list Attribute_Set
		(object Attribute
		    tool       	"Java"
		    name       	"FileName"
		    value      	"java\\nio\\DirectDoubleBufferU.class")
		(object Attribute
		    tool       	"Java"
		    name       	"RootPath"
		    value      	"")
		(object Attribute
		    tool       	"Java"
		    name       	"CmIdentification"
		    value      	(value Text ""))
		(object Attribute
		    tool       	"Java"
		    name       	"CopyrightNotice"
		    value      	(value Text "")))
	    quid       	"3E400F8E0137"
	    stereotype 	""
	    visible_modules 	(list dependency_list
		(object Module_Visibility_Relationship
		    quid       	"3E400F8E02A0"
		    supplier   	"Unsafe"
		    quidu      	"3E400BC4001F"
		    supplier_is_spec 	TRUE)
		(object Module_Visibility_Relationship
		    quid       	"3E400F8E02AA"
		    supplier   	"Component View::java::lang::Class"
		    quidu      	"3E400BBB0176"
		    supplier_is_spec 	TRUE))
	    language   	"Java")
	(object module "DirectFloatBufferRS" "NotAModuleType" "NotAModulePart"
	    attributes 	(list Attribute_Set
		(object Attribute
		    tool       	"Java"
		    name       	"FileName"
		    value      	"java\\nio\\DirectFloatBufferRS.class")
		(object Attribute
		    tool       	"Java"
		    name       	"RootPath"
		    value      	"")
		(object Attribute
		    tool       	"Java"
		    name       	"CmIdentification"
		    value      	(value Text ""))
		(object Attribute
		    tool       	"Java"
		    name       	"CopyrightNotice"
		    value      	(value Text "")))
	    quid       	"3E400F8E03A4"
	    stereotype 	""
	    visible_modules 	(list dependency_list
		(object Module_Visibility_Relationship
		    quid       	"3E400F8F00D4"
		    supplier   	"Component View::java::lang::Class"
		    quidu      	"3E400BBB0176"
		    supplier_is_spec 	TRUE))
	    language   	"Java")
	(object module "DirectFloatBufferRU" "NotAModuleType" "NotAModulePart"
	    attributes 	(list Attribute_Set
		(object Attribute
		    tool       	"Java"
		    name       	"FileName"
		    value      	"java\\nio\\DirectFloatBufferRU.class")
		(object Attribute
		    tool       	"Java"
		    name       	"RootPath"
		    value      	"")
		(object Attribute
		    tool       	"Java"
		    name       	"CmIdentification"
		    value      	(value Text ""))
		(object Attribute
		    tool       	"Java"
		    name       	"CopyrightNotice"
		    value      	(value Text "")))
	    quid       	"3E400F900018"
	    stereotype 	""
	    visible_modules 	(list dependency_list
		(object Module_Visibility_Relationship
		    quid       	"3E400F900126"
		    supplier   	"Component View::java::lang::Class"
		    quidu      	"3E400BBB0176"
		    supplier_is_spec 	TRUE))
	    language   	"Java")
	(object module "DirectShortBufferRS" "NotAModuleType" "NotAModulePart"
	    attributes 	(list Attribute_Set
		(object Attribute
		    tool       	"Java"
		    name       	"FileName"
		    value      	"java\\nio\\DirectShortBufferRS.class")
		(object Attribute
		    tool       	"Java"
		    name       	"RootPath"
		    value      	"")
		(object Attribute
		    tool       	"Java"
		    name       	"CmIdentification"
		    value      	(value Text ""))
		(object Attribute
		    tool       	"Java"
		    name       	"CopyrightNotice"
		    value      	(value Text "")))
	    quid       	"3E400F90022A"
	    stereotype 	""
	    visible_modules 	(list dependency_list
		(object Module_Visibility_Relationship
		    quid       	"3E400F900339"
		    supplier   	"Component View::java::lang::Class"
		    quidu      	"3E400BBB0176"
		    supplier_is_spec 	TRUE))
	    language   	"Java")
	(object module "DirectShortBufferRU" "NotAModuleType" "NotAModulePart"
	    attributes 	(list Attribute_Set
		(object Attribute
		    tool       	"Java"
		    name       	"FileName"
		    value      	"java\\nio\\DirectShortBufferRU.class")
		(object Attribute
		    tool       	"Java"
		    name       	"RootPath"
		    value      	"")
		(object Attribute
		    tool       	"Java"
		    name       	"CmIdentification"
		    value      	(value Text ""))
		(object Attribute
		    tool       	"Java"
		    name       	"CopyrightNotice"
		    value      	(value Text "")))
	    quid       	"3E400F91004B"
	    stereotype 	""
	    visible_modules 	(list dependency_list
		(object Module_Visibility_Relationship
		    quid       	"3E400F910163"
		    supplier   	"Component View::java::lang::Class"
		    quidu      	"3E400BBB0176"
		    supplier_is_spec 	TRUE))
	    language   	"Java")
	(object module "InvalidMarkException" "NotAModuleType" "NotAModulePart"
	    attributes 	(list Attribute_Set
		(object Attribute
		    tool       	"Java"
		    name       	"FileName"
		    value      	"java\\nio\\InvalidMarkException.class")
		(object Attribute
		    tool       	"Java"
		    name       	"RootPath"
		    value      	"")
		(object Attribute
		    tool       	"Java"
		    name       	"CmIdentification"
		    value      	(value Text ""))
		(object Attribute
		    tool       	"Java"
		    name       	"CopyrightNotice"
		    value      	(value Text "")))
	    quid       	"3E401080022F"
	    stereotype 	""
	    language   	"Java")
	(object module "DirectDoubleBufferRU" "NotAModuleType" "NotAModulePart"
	    attributes 	(list Attribute_Set
		(object Attribute
		    tool       	"Java"
		    name       	"FileName"
		    value      	"java\\nio\\DirectDoubleBufferRU.class")
		(object Attribute
		    tool       	"Java"
		    name       	"RootPath"
		    value      	"")
		(object Attribute
		    tool       	"Java"
		    name       	"CmIdentification"
		    value      	(value Text ""))
		(object Attribute
		    tool       	"Java"
		    name       	"CopyrightNotice"
		    value      	(value Text "")))
	    quid       	"3E40108601FC"
	    stereotype 	""
	    visible_modules 	(list dependency_list
		(object Module_Visibility_Relationship
		    quid       	"3E4010860332"
		    supplier   	"Component View::java::lang::Class"
		    quidu      	"3E400BBB0176"
		    supplier_is_spec 	TRUE))
	    language   	"Java")
	(object module "DirectDoubleBufferRS" "NotAModuleType" "NotAModulePart"
	    attributes 	(list Attribute_Set
		(object Attribute
		    tool       	"Java"
		    name       	"FileName"
		    value      	"java\\nio\\DirectDoubleBufferRS.class")
		(object Attribute
		    tool       	"Java"
		    name       	"RootPath"
		    value      	"")
		(object Attribute
		    tool       	"Java"
		    name       	"CmIdentification"
		    value      	(value Text ""))
		(object Attribute
		    tool       	"Java"
		    name       	"CopyrightNotice"
		    value      	(value Text "")))
	    quid       	"3E401087026C"
	    stereotype 	""
	    visible_modules 	(list dependency_list
		(object Module_Visibility_Relationship
		    quid       	"3E40108703A2"
		    supplier   	"Component View::java::lang::Class"
		    quidu      	"3E400BBB0176"
		    supplier_is_spec 	TRUE))
	    language   	"Java")
	(object module "ByteBufferAsIntBufferB" "NotAModuleType" "NotAModulePart"
	    attributes 	(list Attribute_Set
		(object Attribute
		    tool       	"Java"
		    name       	"FileName"
		    value      	"java\\nio\\ByteBufferAsIntBufferB.class")
		(object Attribute
		    tool       	"Java"
		    name       	"RootPath"
		    value      	"")
		(object Attribute
		    tool       	"Java"
		    name       	"CmIdentification"
		    value      	(value Text ""))
		(object Attribute
		    tool       	"Java"
		    name       	"CopyrightNotice"
		    value      	(value Text "")))
	    quid       	"3E4011E100F7"
	    stereotype 	""
	    visible_modules 	(list dependency_list
		(object Module_Visibility_Relationship
		    quid       	"3E4011E1025F"
		    supplier   	"Component View::java::nio::ByteBuffer"
		    quidu      	"3E400BC40092"
		    supplier_is_spec 	TRUE)
		(object Module_Visibility_Relationship
		    quid       	"3E4011E10269"
		    supplier   	"Component View::java::lang::Class"
		    quidu      	"3E400BBB0176"
		    supplier_is_spec 	TRUE))
	    language   	"Java")
	(object module "ByteBufferAsIntBufferL" "NotAModuleType" "NotAModulePart"
	    attributes 	(list Attribute_Set
		(object Attribute
		    tool       	"Java"
		    name       	"FileName"
		    value      	"java\\nio\\ByteBufferAsIntBufferL.class")
		(object Attribute
		    tool       	"Java"
		    name       	"RootPath"
		    value      	"")
		(object Attribute
		    tool       	"Java"
		    name       	"CmIdentification"
		    value      	(value Text ""))
		(object Attribute
		    tool       	"Java"
		    name       	"CopyrightNotice"
		    value      	(value Text "")))
	    quid       	"3E4011E400AB"
	    stereotype 	""
	    visible_modules 	(list dependency_list
		(object Module_Visibility_Relationship
		    quid       	"3E4011E40213"
		    supplier   	"Component View::java::nio::ByteBuffer"
		    quidu      	"3E400BC40092"
		    supplier_is_spec 	TRUE)
		(object Module_Visibility_Relationship
		    quid       	"3E4011E4021D"
		    supplier   	"Component View::java::lang::Class"
		    quidu      	"3E400BBB0176"
		    supplier_is_spec 	TRUE))
	    language   	"Java")
	(object module "BufferOverflowException" "NotAModuleType" "NotAModulePart"
	    attributes 	(list Attribute_Set
		(object Attribute
		    tool       	"Java"
		    name       	"FileName"
		    value      	"java\\nio\\BufferOverflowException.class")
		(object Attribute
		    tool       	"Java"
		    name       	"RootPath"
		    value      	"")
		(object Attribute
		    tool       	"Java"
		    name       	"CmIdentification"
		    value      	(value Text ""))
		(object Attribute
		    tool       	"Java"
		    name       	"CopyrightNotice"
		    value      	(value Text "")))
	    quid       	"3E40121A02F7"
	    stereotype 	""
	    language   	"Java")
	(object module "ReadOnlyBufferException" "NotAModuleType" "NotAModulePart"
	    attributes 	(list Attribute_Set
		(object Attribute
		    tool       	"Java"
		    name       	"FileName"
		    value      	"java\\nio\\ReadOnlyBufferException.class")
		(object Attribute
		    tool       	"Java"
		    name       	"RootPath"
		    value      	"")
		(object Attribute
		    tool       	"Java"
		    name       	"CmIdentification"
		    value      	(value Text ""))
		(object Attribute
		    tool       	"Java"
		    name       	"CopyrightNotice"
		    value      	(value Text "")))
	    quid       	"3E4012510379"
	    stereotype 	""
	    language   	"Java")
	(object module "ByteBufferAsLongBufferL" "NotAModuleType" "NotAModulePart"
	    attributes 	(list Attribute_Set
		(object Attribute
		    tool       	"Java"
		    name       	"FileName"
		    value      	"java\\nio\\ByteBufferAsLongBufferL.class")
		(object Attribute
		    tool       	"Java"
		    name       	"RootPath"
		    value      	"")
		(object Attribute
		    tool       	"Java"
		    name       	"CmIdentification"
		    value      	(value Text ""))
		(object Attribute
		    tool       	"Java"
		    name       	"CopyrightNotice"
		    value      	(value Text "")))
	    quid       	"3E40125402E7"
	    stereotype 	""
	    visible_modules 	(list dependency_list
		(object Module_Visibility_Relationship
		    quid       	"3E401255007B"
		    supplier   	"Component View::java::nio::ByteBuffer"
		    quidu      	"3E400BC40092"
		    supplier_is_spec 	TRUE)
		(object Module_Visibility_Relationship
		    quid       	"3E4012550085"
		    supplier   	"Component View::java::lang::Class"
		    quidu      	"3E400BBB0176"
		    supplier_is_spec 	TRUE))
	    language   	"Java")
	(object module "ByteBufferAsIntBufferRB" "NotAModuleType" "NotAModulePart"
	    attributes 	(list Attribute_Set
		(object Attribute
		    tool       	"Java"
		    name       	"FileName"
		    value      	"java\\nio\\ByteBufferAsIntBufferRB.class")
		(object Attribute
		    tool       	"Java"
		    name       	"RootPath"
		    value      	"")
		(object Attribute
		    tool       	"Java"
		    name       	"CmIdentification"
		    value      	(value Text ""))
		(object Attribute
		    tool       	"Java"
		    name       	"CopyrightNotice"
		    value      	(value Text "")))
	    quid       	"3E40125501F8"
	    stereotype 	""
	    visible_modules 	(list dependency_list
		(object Module_Visibility_Relationship
		    quid       	"3E401255032E"
		    supplier   	"Component View::java::lang::Class"
		    quidu      	"3E400BBB0176"
		    supplier_is_spec 	TRUE))
	    language   	"Java")
	(object module "ByteBufferAsLongBufferB" "NotAModuleType" "NotAModulePart"
	    attributes 	(list Attribute_Set
		(object Attribute
		    tool       	"Java"
		    name       	"FileName"
		    value      	"java\\nio\\ByteBufferAsLongBufferB.class")
		(object Attribute
		    tool       	"Java"
		    name       	"RootPath"
		    value      	"")
		(object Attribute
		    tool       	"Java"
		    name       	"CmIdentification"
		    value      	(value Text ""))
		(object Attribute
		    tool       	"Java"
		    name       	"CopyrightNotice"
		    value      	(value Text "")))
	    quid       	"3E40125600A5"
	    stereotype 	""
	    visible_modules 	(list dependency_list
		(object Module_Visibility_Relationship
		    quid       	"3E4012560217"
		    supplier   	"Component View::java::nio::ByteBuffer"
		    quidu      	"3E400BC40092"
		    supplier_is_spec 	TRUE)
		(object Module_Visibility_Relationship
		    quid       	"3E401256022B"
		    supplier   	"Component View::java::lang::Class"
		    quidu      	"3E400BBB0176"
		    supplier_is_spec 	TRUE))
	    language   	"Java")
	(object module "ByteBufferAsCharBufferL" "NotAModuleType" "NotAModulePart"
	    attributes 	(list Attribute_Set
		(object Attribute
		    tool       	"Java"
		    name       	"FileName"
		    value      	"java\\nio\\ByteBufferAsCharBufferL.class")
		(object Attribute
		    tool       	"Java"
		    name       	"RootPath"
		    value      	"")
		(object Attribute
		    tool       	"Java"
		    name       	"CmIdentification"
		    value      	(value Text ""))
		(object Attribute
		    tool       	"Java"
		    name       	"CopyrightNotice"
		    value      	(value Text "")))
	    quid       	"3E4012570178"
	    stereotype 	""
	    visible_modules 	(list dependency_list
		(object Module_Visibility_Relationship
		    quid       	"3E4012570313"
		    supplier   	"Component View::java::nio::ByteBuffer"
		    quidu      	"3E400BC40092"
		    supplier_is_spec 	TRUE)
		(object Module_Visibility_Relationship
		    quid       	"3E401257031D"
		    supplier   	"Component View::java::lang::Class"
		    quidu      	"3E400BBB0176"
		    supplier_is_spec 	TRUE))
	    language   	"Java")
	(object module "ByteBufferAsCharBufferB" "NotAModuleType" "NotAModulePart"
	    attributes 	(list Attribute_Set
		(object Attribute
		    tool       	"Java"
		    name       	"FileName"
		    value      	"java\\nio\\ByteBufferAsCharBufferB.class")
		(object Attribute
		    tool       	"Java"
		    name       	"RootPath"
		    value      	"")
		(object Attribute
		    tool       	"Java"
		    name       	"CmIdentification"
		    value      	(value Text ""))
		(object Attribute
		    tool       	"Java"
		    name       	"CopyrightNotice"
		    value      	(value Text "")))
	    quid       	"3E4012700070"
	    stereotype 	""
	    visible_modules 	(list dependency_list
		(object Module_Visibility_Relationship
		    quid       	"3E4012700215"
		    supplier   	"Component View::java::nio::ByteBuffer"
		    quidu      	"3E400BC40092"
		    supplier_is_spec 	TRUE)
		(object Module_Visibility_Relationship
		    quid       	"3E401270021F"
		    supplier   	"Component View::java::lang::Class"
		    quidu      	"3E400BBB0176"
		    supplier_is_spec 	TRUE))
	    language   	"Java")
	(object module "ByteBufferAsIntBufferRL" "NotAModuleType" "NotAModulePart"
	    attributes 	(list Attribute_Set
		(object Attribute
		    tool       	"Java"
		    name       	"FileName"
		    value      	"java\\nio\\ByteBufferAsIntBufferRL.class")
		(object Attribute
		    tool       	"Java"
		    name       	"RootPath"
		    value      	"")
		(object Attribute
		    tool       	"Java"
		    name       	"CmIdentification"
		    value      	(value Text ""))
		(object Attribute
		    tool       	"Java"
		    name       	"CopyrightNotice"
		    value      	(value Text "")))
	    quid       	"3E40128E0131"
	    stereotype 	""
	    visible_modules 	(list dependency_list
		(object Module_Visibility_Relationship
		    quid       	"3E40128E0272"
		    supplier   	"Component View::java::lang::Class"
		    quidu      	"3E400BBB0176"
		    supplier_is_spec 	TRUE))
	    language   	"Java")
	(object module "ByteBufferAsFloatBufferL" "NotAModuleType" "NotAModulePart"
	    attributes 	(list Attribute_Set
		(object Attribute
		    tool       	"Java"
		    name       	"FileName"
		    value      	"java\\nio\\ByteBufferAsFloatBufferL.class")
		(object Attribute
		    tool       	"Java"
		    name       	"RootPath"
		    value      	"")
		(object Attribute
		    tool       	"Java"
		    name       	"CmIdentification"
		    value      	(value Text ""))
		(object Attribute
		    tool       	"Java"
		    name       	"CopyrightNotice"
		    value      	(value Text "")))
	    quid       	"3E401295027C"
	    stereotype 	""
	    visible_modules 	(list dependency_list
		(object Module_Visibility_Relationship
		    quid       	"3E4012960010"
		    supplier   	"Component View::java::nio::ByteBuffer"
		    quidu      	"3E400BC40092"
		    supplier_is_spec 	TRUE)
		(object Module_Visibility_Relationship
		    quid       	"3E4012960025"
		    supplier   	"Component View::java::lang::Class"
		    quidu      	"3E400BBB0176"
		    supplier_is_spec 	TRUE))
	    language   	"Java")
	(object module "ByteBufferAsCharBufferRB" "NotAModuleType" "NotAModulePart"
	    attributes 	(list Attribute_Set
		(object Attribute
		    tool       	"Java"
		    name       	"FileName"
		    value      	"java\\nio\\ByteBufferAsCharBufferRB.class")
		(object Attribute
		    tool       	"Java"
		    name       	"RootPath"
		    value      	"")
		(object Attribute
		    tool       	"Java"
		    name       	"CmIdentification"
		    value      	(value Text ""))
		(object Attribute
		    tool       	"Java"
		    name       	"CopyrightNotice"
		    value      	(value Text "")))
	    quid       	"3E4012A302A4"
	    stereotype 	""
	    visible_modules 	(list dependency_list
		(object Module_Visibility_Relationship
		    quid       	"3E4012A40025"
		    supplier   	"Component View::java::lang::Class"
		    quidu      	"3E400BBB0176"
		    supplier_is_spec 	TRUE))
	    language   	"Java")
	(object module "ByteBufferAsCharBufferRL" "NotAModuleType" "NotAModulePart"
	    attributes 	(list Attribute_Set
		(object Attribute
		    tool       	"Java"
		    name       	"FileName"
		    value      	"java\\nio\\ByteBufferAsCharBufferRL.class")
		(object Attribute
		    tool       	"Java"
		    name       	"RootPath"
		    value      	"")
		(object Attribute
		    tool       	"Java"
		    name       	"CmIdentification"
		    value      	(value Text ""))
		(object Attribute
		    tool       	"Java"
		    name       	"CopyrightNotice"
		    value      	(value Text "")))
	    quid       	"3E4012A50080"
	    stereotype 	""
	    visible_modules 	(list dependency_list
		(object Module_Visibility_Relationship
		    quid       	"3E4012A501E9"
		    supplier   	"Component View::java::lang::Class"
		    quidu      	"3E400BBB0176"
		    supplier_is_spec 	TRUE))
	    language   	"Java")
	(object module "ByteBufferAsFloatBufferB" "NotAModuleType" "NotAModulePart"
	    attributes 	(list Attribute_Set
		(object Attribute
		    tool       	"Java"
		    name       	"FileName"
		    value      	"java\\nio\\ByteBufferAsFloatBufferB.class")
		(object Attribute
		    tool       	"Java"
		    name       	"RootPath"
		    value      	"")
		(object Attribute
		    tool       	"Java"
		    name       	"CmIdentification"
		    value      	(value Text ""))
		(object Attribute
		    tool       	"Java"
		    name       	"CopyrightNotice"
		    value      	(value Text "")))
	    quid       	"3E4012A80099"
	    stereotype 	""
	    visible_modules 	(list dependency_list
		(object Module_Visibility_Relationship
		    quid       	"3E4012A80215"
		    supplier   	"Component View::java::nio::ByteBuffer"
		    quidu      	"3E400BC40092"
		    supplier_is_spec 	TRUE)
		(object Module_Visibility_Relationship
		    quid       	"3E4012A80229"
		    supplier   	"Component View::java::lang::Class"
		    quidu      	"3E400BBB0176"
		    supplier_is_spec 	TRUE))
	    language   	"Java")
	(object module "ByteBufferAsShortBufferB" "NotAModuleType" "NotAModulePart"
	    attributes 	(list Attribute_Set
		(object Attribute
		    tool       	"Java"
		    name       	"FileName"
		    value      	"java\\nio\\ByteBufferAsShortBufferB.class")
		(object Attribute
		    tool       	"Java"
		    name       	"RootPath"
		    value      	"")
		(object Attribute
		    tool       	"Java"
		    name       	"CmIdentification"
		    value      	(value Text ""))
		(object Attribute
		    tool       	"Java"
		    name       	"CopyrightNotice"
		    value      	(value Text "")))
	    quid       	"3E4012AE039A"
	    stereotype 	""
	    visible_modules 	(list dependency_list
		(object Module_Visibility_Relationship
		    quid       	"3E4012AF012F"
		    supplier   	"Component View::java::nio::ByteBuffer"
		    quidu      	"3E400BC40092"
		    supplier_is_spec 	TRUE)
		(object Module_Visibility_Relationship
		    quid       	"3E4012AF0143"
		    supplier   	"Component View::java::lang::Class"
		    quidu      	"3E400BBB0176"
		    supplier_is_spec 	TRUE))
	    language   	"Java")
	(object module "ByteBufferAsShortBufferL" "NotAModuleType" "NotAModulePart"
	    attributes 	(list Attribute_Set
		(object Attribute
		    tool       	"Java"
		    name       	"FileName"
		    value      	"java\\nio\\ByteBufferAsShortBufferL.class")
		(object Attribute
		    tool       	"Java"
		    name       	"RootPath"
		    value      	"")
		(object Attribute
		    tool       	"Java"
		    name       	"CmIdentification"
		    value      	(value Text ""))
		(object Attribute
		    tool       	"Java"
		    name       	"CopyrightNotice"
		    value      	(value Text "")))
	    quid       	"3E4012B102EA"
	    stereotype 	""
	    visible_modules 	(list dependency_list
		(object Module_Visibility_Relationship
		    quid       	"3E4012B2007F"
		    supplier   	"Component View::java::nio::ByteBuffer"
		    quidu      	"3E400BC40092"
		    supplier_is_spec 	TRUE)
		(object Module_Visibility_Relationship
		    quid       	"3E4012B20093"
		    supplier   	"Component View::java::lang::Class"
		    quidu      	"3E400BBB0176"
		    supplier_is_spec 	TRUE))
	    language   	"Java")
	(object module "ByteBufferAsLongBufferRL" "NotAModuleType" "NotAModulePart"
	    attributes 	(list Attribute_Set
		(object Attribute
		    tool       	"Java"
		    name       	"FileName"
		    value      	"java\\nio\\ByteBufferAsLongBufferRL.class")
		(object Attribute
		    tool       	"Java"
		    name       	"RootPath"
		    value      	"")
		(object Attribute
		    tool       	"Java"
		    name       	"CmIdentification"
		    value      	(value Text ""))
		(object Attribute
		    tool       	"Java"
		    name       	"CopyrightNotice"
		    value      	(value Text "")))
	    quid       	"3E4012BE016C"
	    stereotype 	""
	    visible_modules 	(list dependency_list
		(object Module_Visibility_Relationship
		    quid       	"3E4012BE02AD"
		    supplier   	"Component View::java::lang::Class"
		    quidu      	"3E400BBB0176"
		    supplier_is_spec 	TRUE))
	    language   	"Java")
	(object module "ByteBufferAsLongBufferRB" "NotAModuleType" "NotAModulePart"
	    attributes 	(list Attribute_Set
		(object Attribute
		    tool       	"Java"
		    name       	"FileName"
		    value      	"java\\nio\\ByteBufferAsLongBufferRB.class")
		(object Attribute
		    tool       	"Java"
		    name       	"RootPath"
		    value      	"")
		(object Attribute
		    tool       	"Java"
		    name       	"CmIdentification"
		    value      	(value Text ""))
		(object Attribute
		    tool       	"Java"
		    name       	"CopyrightNotice"
		    value      	(value Text "")))
	    quid       	"3E4012BF002D"
	    stereotype 	""
	    visible_modules 	(list dependency_list
		(object Module_Visibility_Relationship
		    quid       	"3E4012BF0178"
		    supplier   	"Component View::java::lang::Class"
		    quidu      	"3E400BBB0176"
		    supplier_is_spec 	TRUE))
	    language   	"Java")
	(object module "BufferUnderflowException" "NotAModuleType" "NotAModulePart"
	    attributes 	(list Attribute_Set
		(object Attribute
		    tool       	"Java"
		    name       	"FileName"
		    value      	"java\\nio\\BufferUnderflowException.class")
		(object Attribute
		    tool       	"Java"
		    name       	"RootPath"
		    value      	"")
		(object Attribute
		    tool       	"Java"
		    name       	"CmIdentification"
		    value      	(value Text ""))
		(object Attribute
		    tool       	"Java"
		    name       	"CopyrightNotice"
		    value      	(value Text "")))
	    quid       	"3E401305015B"
	    stereotype 	""
	    language   	"Java")
	(object module "ByteBufferAsShortBufferRL" "NotAModuleType" "NotAModulePart"
	    attributes 	(list Attribute_Set
		(object Attribute
		    tool       	"Java"
		    name       	"FileName"
		    value      	"java\\nio\\ByteBufferAsShortBufferRL.class")
		(object Attribute
		    tool       	"Java"
		    name       	"RootPath"
		    value      	"")
		(object Attribute
		    tool       	"Java"
		    name       	"CmIdentification"
		    value      	(value Text ""))
		(object Attribute
		    tool       	"Java"
		    name       	"CopyrightNotice"
		    value      	(value Text "")))
	    quid       	"3E4013930295"
	    stereotype 	""
	    visible_modules 	(list dependency_list
		(object Module_Visibility_Relationship
		    quid       	"3E401394000C"
		    supplier   	"Component View::java::lang::Class"
		    quidu      	"3E400BBB0176"
		    supplier_is_spec 	TRUE))
	    language   	"Java")
	(object module "ByteBufferAsShortBufferRB" "NotAModuleType" "NotAModulePart"
	    attributes 	(list Attribute_Set
		(object Attribute
		    tool       	"Java"
		    name       	"FileName"
		    value      	"java\\nio\\ByteBufferAsShortBufferRB.class")
		(object Attribute
		    tool       	"Java"
		    name       	"RootPath"
		    value      	"")
		(object Attribute
		    tool       	"Java"
		    name       	"CmIdentification"
		    value      	(value Text ""))
		(object Attribute
		    tool       	"Java"
		    name       	"CopyrightNotice"
		    value      	(value Text "")))
	    quid       	"3E401394011A"
	    stereotype 	""
	    visible_modules 	(list dependency_list
		(object Module_Visibility_Relationship
		    quid       	"3E4013940283"
		    supplier   	"Component View::java::lang::Class"
		    quidu      	"3E400BBB0176"
		    supplier_is_spec 	TRUE))
	    language   	"Java")
	(object module "ByteBufferAsDoubleBufferL" "NotAModuleType" "NotAModulePart"
	    attributes 	(list Attribute_Set
		(object Attribute
		    tool       	"Java"
		    name       	"FileName"
		    value      	"java\\nio\\ByteBufferAsDoubleBufferL.class")
		(object Attribute
		    tool       	"Java"
		    name       	"RootPath"
		    value      	"")
		(object Attribute
		    tool       	"Java"
		    name       	"CmIdentification"
		    value      	(value Text ""))
		(object Attribute
		    tool       	"Java"
		    name       	"CopyrightNotice"
		    value      	(value Text "")))
	    quid       	"3E4013C501C5"
	    stereotype 	""
	    visible_modules 	(list dependency_list
		(object Module_Visibility_Relationship
		    quid       	"3E4013C50369"
		    supplier   	"Component View::java::nio::ByteBuffer"
		    quidu      	"3E400BC40092"
		    supplier_is_spec 	TRUE)
		(object Module_Visibility_Relationship
		    quid       	"3E4013C5037D"
		    supplier   	"Component View::java::lang::Class"
		    quidu      	"3E400BBB0176"
		    supplier_is_spec 	TRUE))
	    language   	"Java")
	(object module "ByteBufferAsDoubleBufferB" "NotAModuleType" "NotAModulePart"
	    attributes 	(list Attribute_Set
		(object Attribute
		    tool       	"Java"
		    name       	"FileName"
		    value      	"java\\nio\\ByteBufferAsDoubleBufferB.class")
		(object Attribute
		    tool       	"Java"
		    name       	"RootPath"
		    value      	"")
		(object Attribute
		    tool       	"Java"
		    name       	"CmIdentification"
		    value      	(value Text ""))
		(object Attribute
		    tool       	"Java"
		    name       	"CopyrightNotice"
		    value      	(value Text "")))
	    quid       	"3E4013C60202"
	    stereotype 	""
	    visible_modules 	(list dependency_list
		(object Module_Visibility_Relationship
		    quid       	"3E4013C603A7"
		    supplier   	"Component View::java::nio::ByteBuffer"
		    quidu      	"3E400BC40092"
		    supplier_is_spec 	TRUE)
		(object Module_Visibility_Relationship
		    quid       	"3E4013C603BB"
		    supplier   	"Component View::java::lang::Class"
		    quidu      	"3E400BBB0176"
		    supplier_is_spec 	TRUE))
	    language   	"Java")
	(object module "ByteBufferAsFloatBufferRL" "NotAModuleType" "NotAModulePart"
	    attributes 	(list Attribute_Set
		(object Attribute
		    tool       	"Java"
		    name       	"FileName"
		    value      	"java\\nio\\ByteBufferAsFloatBufferRL.class")
		(object Attribute
		    tool       	"Java"
		    name       	"RootPath"
		    value      	"")
		(object Attribute
		    tool       	"Java"
		    name       	"CmIdentification"
		    value      	(value Text ""))
		(object Attribute
		    tool       	"Java"
		    name       	"CopyrightNotice"
		    value      	(value Text "")))
	    quid       	"3E4013C800E3"
	    stereotype 	""
	    visible_modules 	(list dependency_list
		(object Module_Visibility_Relationship
		    quid       	"3E4013C8024B"
		    supplier   	"Component View::java::lang::Class"
		    quidu      	"3E400BBB0176"
		    supplier_is_spec 	TRUE))
	    language   	"Java")
	(object module "ByteBufferAsFloatBufferRB" "NotAModuleType" "NotAModulePart"
	    attributes 	(list Attribute_Set
		(object Attribute
		    tool       	"Java"
		    name       	"FileName"
		    value      	"java\\nio\\ByteBufferAsFloatBufferRB.class")
		(object Attribute
		    tool       	"Java"
		    name       	"RootPath"
		    value      	"")
		(object Attribute
		    tool       	"Java"
		    name       	"CmIdentification"
		    value      	(value Text ""))
		(object Attribute
		    tool       	"Java"
		    name       	"CopyrightNotice"
		    value      	(value Text "")))
	    quid       	"3E4013CB0029"
	    stereotype 	""
	    visible_modules 	(list dependency_list
		(object Module_Visibility_Relationship
		    quid       	"3E4013CB0191"
		    supplier   	"Component View::java::lang::Class"
		    quidu      	"3E400BBB0176"
		    supplier_is_spec 	TRUE))
	    language   	"Java")
	(object module "ByteBufferAsDoubleBufferRL" "NotAModuleType" "NotAModulePart"
	    attributes 	(list Attribute_Set
		(object Attribute
		    tool       	"Java"
		    name       	"FileName"
		    value      	"java\\nio\\ByteBufferAsDoubleBufferRL.class")
		(object Attribute
		    tool       	"Java"
		    name       	"RootPath"
		    value      	"")
		(object Attribute
		    tool       	"Java"
		    name       	"CmIdentification"
		    value      	(value Text ""))
		(object Attribute
		    tool       	"Java"
		    name       	"CopyrightNotice"
		    value      	(value Text "")))
	    quid       	"3E40149D0234"
	    stereotype 	""
	    visible_modules 	(list dependency_list
		(object Module_Visibility_Relationship
		    quid       	"3E40149D03BA"
		    supplier   	"Component View::java::lang::Class"
		    quidu      	"3E400BBB0176"
		    supplier_is_spec 	TRUE))
	    language   	"Java")
	(object module "ByteBufferAsDoubleBufferRB" "NotAModuleType" "NotAModulePart"
	    attributes 	(list Attribute_Set
		(object Attribute
		    tool       	"Java"
		    name       	"FileName"
		    value      	"java\\nio\\ByteBufferAsDoubleBufferRB.class")
		(object Attribute
		    tool       	"Java"
		    name       	"RootPath"
		    value      	"")
		(object Attribute
		    tool       	"Java"
		    name       	"CmIdentification"
		    value      	(value Text ""))
		(object Attribute
		    tool       	"Java"
		    name       	"CopyrightNotice"
		    value      	(value Text "")))
	    quid       	"3E4014A403BA"
	    stereotype 	""
	    visible_modules 	(list dependency_list
		(object Module_Visibility_Relationship
		    quid       	"3E4014A5014F"
		    supplier   	"Component View::java::lang::Class"
		    quidu      	"3E400BBB0176"
		    supplier_is_spec 	TRUE))
	    language   	"Java")
	(object SubSystem "channels"
	    quid       	"3E400BE30369"
	    visible_modules 	(list dependency_list
		(object Module_Visibility_Relationship
		    quid       	"3E401D9D0164"
		    supplier   	"Component View::java::io"
		    quidu      	"3E400BBB02C0"
		    supplier_is_subsystem 	TRUE))
	    physical_models 	(list unit_reference_list
		(object module "SocketChannel" "NotAModuleType" "NotAModulePart"
		    attributes 	(list Attribute_Set
			(object Attribute
			    tool       	"Java"
			    name       	"FileName"
			    value      	"java\\nio\\channels\\SocketChannel.class")
			(object Attribute
			    tool       	"Java"
			    name       	"RootPath"
			    value      	"")
			(object Attribute
			    tool       	"Java"
			    name       	"CmIdentification"
			    value      	(value Text ""))
			(object Attribute
			    tool       	"Java"
			    name       	"CopyrightNotice"
			    value      	(value Text "")))
		    quid       	"3E400BE3036A"
		    stereotype 	""
		    language   	"Java")
		(object module "Selector" "NotAModuleType" "NotAModulePart"
		    attributes 	(list Attribute_Set
			(object Attribute
			    tool       	"Java"
			    name       	"FileName"
			    value      	"java\\nio\\channels\\Selector.class")
			(object Attribute
			    tool       	"Java"
			    name       	"RootPath"
			    value      	"")
			(object Attribute
			    tool       	"Java"
			    name       	"CmIdentification"
			    value      	(value Text ""))
			(object Attribute
			    tool       	"Java"
			    name       	"CopyrightNotice"
			    value      	(value Text "")))
		    quid       	"3E400BE50054"
		    stereotype 	""
		    language   	"Java")
		(object module "SelectableChannel" "NotAModuleType" "NotAModulePart"
		    attributes 	(list Attribute_Set
			(object Attribute
			    tool       	"Java"
			    name       	"FileName"
			    value      	"java\\nio\\channels\\SelectableChannel.class")
			(object Attribute
			    tool       	"Java"
			    name       	"RootPath"
			    value      	"")
			(object Attribute
			    tool       	"Java"
			    name       	"CmIdentification"
			    value      	(value Text ""))
			(object Attribute
			    tool       	"Java"
			    name       	"CopyrightNotice"
			    value      	(value Text "")))
		    quid       	"3E400BE5005D"
		    stereotype 	""
		    language   	"Java")
		(object module "Pipe" "NotAModuleType" "NotAModulePart"
		    attributes 	(list Attribute_Set
			(object Attribute
			    tool       	"Java"
			    name       	"FileName"
			    value      	"java\\nio\\channels\\Pipe.class")
			(object Attribute
			    tool       	"Java"
			    name       	"RootPath"
			    value      	"")
			(object Attribute
			    tool       	"Java"
			    name       	"CmIdentification"
			    value      	(value Text ""))
			(object Attribute
			    tool       	"Java"
			    name       	"CopyrightNotice"
			    value      	(value Text "")))
		    quid       	"3E400C6C02EC"
		    stereotype 	""
		    language   	"Java")
		(object module "Pipe$SourceChannel" "NotAModuleType" "NotAModulePart"
		    attributes 	(list Attribute_Set
			(object Attribute
			    tool       	"Java"
			    name       	"FileName"
			    value      	"java\\nio\\channels\\Pipe$SourceChannel.class")
			(object Attribute
			    tool       	"Java"
			    name       	"RootPath"
			    value      	"")
			(object Attribute
			    tool       	"Java"
			    name       	"CmIdentification"
			    value      	(value Text ""))
			(object Attribute
			    tool       	"Java"
			    name       	"CopyrightNotice"
			    value      	(value Text "")))
		    quid       	"3E400C6C0398"
		    stereotype 	""
		    language   	"Java")
		(object module "Pipe$SinkChannel" "NotAModuleType" "NotAModulePart"
		    attributes 	(list Attribute_Set
			(object Attribute
			    tool       	"Java"
			    name       	"FileName"
			    value      	"java\\nio\\channels\\Pipe$SinkChannel.class")
			(object Attribute
			    tool       	"Java"
			    name       	"RootPath"
			    value      	"")
			(object Attribute
			    tool       	"Java"
			    name       	"CmIdentification"
			    value      	(value Text ""))
			(object Attribute
			    tool       	"Java"
			    name       	"CopyrightNotice"
			    value      	(value Text "")))
		    quid       	"3E400C6C03A1"
		    stereotype 	""
		    language   	"Java")
		(object module "ServerSocketChannel" "NotAModuleType" "NotAModulePart"
		    attributes 	(list Attribute_Set
			(object Attribute
			    tool       	"Java"
			    name       	"FileName"
			    value      	"java\\nio\\channels\\ServerSocketChannel.class")
			(object Attribute
			    tool       	"Java"
			    name       	"RootPath"
			    value      	"")
			(object Attribute
			    tool       	"Java"
			    name       	"CmIdentification"
			    value      	(value Text ""))
			(object Attribute
			    tool       	"Java"
			    name       	"CopyrightNotice"
			    value      	(value Text "")))
		    quid       	"3E400CB2026C"
		    stereotype 	""
		    language   	"Java")
		(object module "DatagramChannel" "NotAModuleType" "NotAModulePart"
		    attributes 	(list Attribute_Set
			(object Attribute
			    tool       	"Java"
			    name       	"FileName"
			    value      	"java\\nio\\channels\\DatagramChannel.class")
			(object Attribute
			    tool       	"Java"
			    name       	"RootPath"
			    value      	"")
			(object Attribute
			    tool       	"Java"
			    name       	"CmIdentification"
			    value      	(value Text ""))
			(object Attribute
			    tool       	"Java"
			    name       	"CopyrightNotice"
			    value      	(value Text "")))
		    quid       	"3E400D58026A"
		    stereotype 	""
		    language   	"Java")
		(object module "SelectionKey" "NotAModuleType" "NotAModulePart"
		    attributes 	(list Attribute_Set
			(object Attribute
			    tool       	"Java"
			    name       	"FileName"
			    value      	"java\\nio\\channels\\SelectionKey.class")
			(object Attribute
			    tool       	"Java"
			    name       	"RootPath"
			    value      	"")
			(object Attribute
			    tool       	"Java"
			    name       	"CmIdentification"
			    value      	(value Text ""))
			(object Attribute
			    tool       	"Java"
			    name       	"CopyrightNotice"
			    value      	(value Text "")))
		    quid       	"3E400D5F0256"
		    stereotype 	""
		    language   	"Java")
		(object module "FileChannel" "NotAModuleType" "NotAModulePart"
		    attributes 	(list Attribute_Set
			(object Attribute
			    tool       	"Java"
			    name       	"FileName"
			    value      	"java\\nio\\channels\\FileChannel.class")
			(object Attribute
			    tool       	"Java"
			    name       	"RootPath"
			    value      	"")
			(object Attribute
			    tool       	"Java"
			    name       	"CmIdentification"
			    value      	(value Text ""))
			(object Attribute
			    tool       	"Java"
			    name       	"CopyrightNotice"
			    value      	(value Text "")))
		    quid       	"3E400D7A0178"
		    stereotype 	""
		    language   	"Java")
		(object module "FileLock" "NotAModuleType" "NotAModulePart"
		    attributes 	(list Attribute_Set
			(object Attribute
			    tool       	"Java"
			    name       	"FileName"
			    value      	"java\\nio\\channels\\FileLock.class")
			(object Attribute
			    tool       	"Java"
			    name       	"RootPath"
			    value      	"")
			(object Attribute
			    tool       	"Java"
			    name       	"CmIdentification"
			    value      	(value Text ""))
			(object Attribute
			    tool       	"Java"
			    name       	"CopyrightNotice"
			    value      	(value Text "")))
		    quid       	"3E400D9102D0"
		    stereotype 	""
		    visible_modules 	(list dependency_list
			(object Module_Visibility_Relationship
			    quid       	"3E400E9D009A"
			    supplier   	"Component View::java::nio::channels::FileChannel"
			    quidu      	"3E400D7A0178"
			    supplier_is_spec 	TRUE))
		    language   	"Java")
		(object module "WritableByteChannel" "NotAModuleType" "NotAModulePart"
		    attributes 	(list Attribute_Set
			(object Attribute
			    tool       	"Java"
			    name       	"FileName"
			    value      	"java\\nio\\channels\\WritableByteChannel.class")
			(object Attribute
			    tool       	"Java"
			    name       	"RootPath"
			    value      	"")
			(object Attribute
			    tool       	"Java"
			    name       	"CmIdentification"
			    value      	(value Text ""))
			(object Attribute
			    tool       	"Java"
			    name       	"CopyrightNotice"
			    value      	(value Text "")))
		    quid       	"3E400DA601FE"
		    stereotype 	""
		    language   	"Java")
		(object module "ReadableByteChannel" "NotAModuleType" "NotAModulePart"
		    attributes 	(list Attribute_Set
			(object Attribute
			    tool       	"Java"
			    name       	"FileName"
			    value      	"java\\nio\\channels\\ReadableByteChannel.class")
			(object Attribute
			    tool       	"Java"
			    name       	"RootPath"
			    value      	"")
			(object Attribute
			    tool       	"Java"
			    name       	"CmIdentification"
			    value      	(value Text ""))
			(object Attribute
			    tool       	"Java"
			    name       	"CopyrightNotice"
			    value      	(value Text "")))
		    quid       	"3E400DA903E3"
		    stereotype 	""
		    language   	"Java")
		(object module "Channel" "NotAModuleType" "NotAModulePart"
		    attributes 	(list Attribute_Set
			(object Attribute
			    tool       	"Java"
			    name       	"FileName"
			    value      	"java\\nio\\channels\\Channel.class")
			(object Attribute
			    tool       	"Java"
			    name       	"RootPath"
			    value      	"")
			(object Attribute
			    tool       	"Java"
			    name       	"CmIdentification"
			    value      	(value Text ""))
			(object Attribute
			    tool       	"Java"
			    name       	"CopyrightNotice"
			    value      	(value Text "")))
		    quid       	"3E400E5E037F"
		    stereotype 	""
		    language   	"Java")
		(object module "Channels" "NotAModuleType" "NotAModulePart"
		    attributes 	(list Attribute_Set
			(object Attribute
			    tool       	"Java"
			    name       	"FileName"
			    value      	"java\\nio\\channels\\Channels.class")
			(object Attribute
			    tool       	"Java"
			    name       	"RootPath"
			    value      	"")
			(object Attribute
			    tool       	"Java"
			    name       	"CmIdentification"
			    value      	(value Text ""))
			(object Attribute
			    tool       	"Java"
			    name       	"CopyrightNotice"
			    value      	(value Text "")))
		    quid       	"3E400EA0035C"
		    stereotype 	""
		    language   	"Java")
		(object module "OverlappingFileLockException" "NotAModuleType" "NotAModulePart"
		    attributes 	(list Attribute_Set
			(object Attribute
			    tool       	"Java"
			    name       	"FileName"
			    value      	"java\\nio\\channels\\OverlappingFileLockException.class")
			(object Attribute
			    tool       	"Java"
			    name       	"RootPath"
			    value      	"")
			(object Attribute
			    tool       	"Java"
			    name       	"CmIdentification"
			    value      	(value Text ""))
			(object Attribute
			    tool       	"Java"
			    name       	"CopyrightNotice"
			    value      	(value Text "")))
		    quid       	"3E400ED800BD"
		    stereotype 	""
		    language   	"Java")
		(object module "ClosedChannelException" "NotAModuleType" "NotAModulePart"
		    attributes 	(list Attribute_Set
			(object Attribute
			    tool       	"Java"
			    name       	"FileName"
			    value      	"java\\nio\\channels\\ClosedChannelException.class")
			(object Attribute
			    tool       	"Java"
			    name       	"RootPath"
			    value      	"")
			(object Attribute
			    tool       	"Java"
			    name       	"CmIdentification"
			    value      	(value Text ""))
			(object Attribute
			    tool       	"Java"
			    name       	"CopyrightNotice"
			    value      	(value Text "")))
		    quid       	"3E400FA203CB"
		    stereotype 	""
		    language   	"Java")
		(object module "ByteChannel" "NotAModuleType" "NotAModulePart"
		    attributes 	(list Attribute_Set
			(object Attribute
			    tool       	"Java"
			    name       	"FileName"
			    value      	"java\\nio\\channels\\ByteChannel.class")
			(object Attribute
			    tool       	"Java"
			    name       	"RootPath"
			    value      	"")
			(object Attribute
			    tool       	"Java"
			    name       	"CmIdentification"
			    value      	(value Text ""))
			(object Attribute
			    tool       	"Java"
			    name       	"CopyrightNotice"
			    value      	(value Text "")))
		    quid       	"3E40107A021D"
		    stereotype 	""
		    language   	"Java")
		(object module "FileChannel$MapMode" "NotAModuleType" "NotAModulePart"
		    attributes 	(list Attribute_Set
			(object Attribute
			    tool       	"Java"
			    name       	"FileName"
			    value      	"java\\nio\\channels\\FileChannel$MapMode.class")
			(object Attribute
			    tool       	"Java"
			    name       	"RootPath"
			    value      	"")
			(object Attribute
			    tool       	"Java"
			    name       	"CmIdentification"
			    value      	(value Text ""))
			(object Attribute
			    tool       	"Java"
			    name       	"CopyrightNotice"
			    value      	(value Text "")))
		    quid       	"3E4015D60125"
		    stereotype 	""
		    language   	"Java")
		(object module "GatheringByteChannel" "NotAModuleType" "NotAModulePart"
		    attributes 	(list Attribute_Set
			(object Attribute
			    tool       	"Java"
			    name       	"FileName"
			    value      	"java\\nio\\channels\\GatheringByteChannel.class")
			(object Attribute
			    tool       	"Java"
			    name       	"RootPath"
			    value      	"")
			(object Attribute
			    tool       	"Java"
			    name       	"CmIdentification"
			    value      	(value Text ""))
			(object Attribute
			    tool       	"Java"
			    name       	"CopyrightNotice"
			    value      	(value Text "")))
		    quid       	"3E40165E00D1"
		    stereotype 	""
		    language   	"Java")
		(object module "NotYetBoundException" "NotAModuleType" "NotAModulePart"
		    attributes 	(list Attribute_Set
			(object Attribute
			    tool       	"Java"
			    name       	"FileName"
			    value      	"java\\nio\\channels\\NotYetBoundException.class")
			(object Attribute
			    tool       	"Java"
			    name       	"RootPath"
			    value      	"")
			(object Attribute
			    tool       	"Java"
			    name       	"CmIdentification"
			    value      	(value Text ""))
			(object Attribute
			    tool       	"Java"
			    name       	"CopyrightNotice"
			    value      	(value Text "")))
		    quid       	"3E4016FA012F"
		    stereotype 	""
		    language   	"Java")
		(object module "InterruptibleChannel" "NotAModuleType" "NotAModulePart"
		    attributes 	(list Attribute_Set
			(object Attribute
			    tool       	"Java"
			    name       	"FileName"
			    value      	"java\\nio\\channels\\InterruptibleChannel.class")
			(object Attribute
			    tool       	"Java"
			    name       	"RootPath"
			    value      	"")
			(object Attribute
			    tool       	"Java"
			    name       	"CmIdentification"
			    value      	(value Text ""))
			(object Attribute
			    tool       	"Java"
			    name       	"CopyrightNotice"
			    value      	(value Text "")))
		    quid       	"3E4016FA01CF"
		    stereotype 	""
		    language   	"Java")
		(object module "CancelledKeyException" "NotAModuleType" "NotAModulePart"
		    attributes 	(list Attribute_Set
			(object Attribute
			    tool       	"Java"
			    name       	"FileName"
			    value      	"java\\nio\\channels\\CancelledKeyException.class")
			(object Attribute
			    tool       	"Java"
			    name       	"RootPath"
			    value      	"")
			(object Attribute
			    tool       	"Java"
			    name       	"CmIdentification"
			    value      	(value Text ""))
			(object Attribute
			    tool       	"Java"
			    name       	"CopyrightNotice"
			    value      	(value Text "")))
		    quid       	"3E4017070391"
		    stereotype 	""
		    language   	"Java")
		(object module "ScatteringByteChannel" "NotAModuleType" "NotAModulePart"
		    attributes 	(list Attribute_Set
			(object Attribute
			    tool       	"Java"
			    name       	"FileName"
			    value      	"java\\nio\\channels\\ScatteringByteChannel.class")
			(object Attribute
			    tool       	"Java"
			    name       	"RootPath"
			    value      	"")
			(object Attribute
			    tool       	"Java"
			    name       	"CmIdentification"
			    value      	(value Text ""))
			(object Attribute
			    tool       	"Java"
			    name       	"CopyrightNotice"
			    value      	(value Text "")))
		    quid       	"3E40177C0096"
		    stereotype 	""
		    language   	"Java")
		(object module "ClosedSelectorException" "NotAModuleType" "NotAModulePart"
		    attributes 	(list Attribute_Set
			(object Attribute
			    tool       	"Java"
			    name       	"FileName"
			    value      	"java\\nio\\channels\\ClosedSelectorException.class")
			(object Attribute
			    tool       	"Java"
			    name       	"RootPath"
			    value      	"")
			(object Attribute
			    tool       	"Java"
			    name       	"CmIdentification"
			    value      	(value Text ""))
			(object Attribute
			    tool       	"Java"
			    name       	"CopyrightNotice"
			    value      	(value Text "")))
		    quid       	"3E4018BB0329"
		    stereotype 	""
		    language   	"Java")
		(object module "NotYetConnectedException" "NotAModuleType" "NotAModulePart"
		    attributes 	(list Attribute_Set
			(object Attribute
			    tool       	"Java"
			    name       	"FileName"
			    value      	"java\\nio\\channels\\NotYetConnectedException.class")
			(object Attribute
			    tool       	"Java"
			    name       	"RootPath"
			    value      	"")
			(object Attribute
			    tool       	"Java"
			    name       	"CmIdentification"
			    value      	(value Text ""))
			(object Attribute
			    tool       	"Java"
			    name       	"CopyrightNotice"
			    value      	(value Text "")))
		    quid       	"3E40199502E7"
		    stereotype 	""
		    language   	"Java")
		(object module "IllegalSelectorException" "NotAModuleType" "NotAModulePart"
		    attributes 	(list Attribute_Set
			(object Attribute
			    tool       	"Java"
			    name       	"FileName"
			    value      	"java\\nio\\channels\\IllegalSelectorException.class")
			(object Attribute
			    tool       	"Java"
			    name       	"RootPath"
			    value      	"")
			(object Attribute
			    tool       	"Java"
			    name       	"CmIdentification"
			    value      	(value Text ""))
			(object Attribute
			    tool       	"Java"
			    name       	"CopyrightNotice"
			    value      	(value Text "")))
		    quid       	"3E4019950387"
		    stereotype 	""
		    language   	"Java")
		(object module "AlreadyConnectedException" "NotAModuleType" "NotAModulePart"
		    attributes 	(list Attribute_Set
			(object Attribute
			    tool       	"Java"
			    name       	"FileName"
			    value      	"java\\nio\\channels\\AlreadyConnectedException.class")
			(object Attribute
			    tool       	"Java"
			    name       	"RootPath"
			    value      	"")
			(object Attribute
			    tool       	"Java"
			    name       	"CmIdentification"
			    value      	(value Text ""))
			(object Attribute
			    tool       	"Java"
			    name       	"CopyrightNotice"
			    value      	(value Text "")))
		    quid       	"3E4019E600E5"
		    stereotype 	""
		    language   	"Java")
		(object module "AsynchronousCloseException" "NotAModuleType" "NotAModulePart"
		    attributes 	(list Attribute_Set
			(object Attribute
			    tool       	"Java"
			    name       	"FileName"
			    value      	"java\\nio\\channels\\AsynchronousCloseException.class")
			(object Attribute
			    tool       	"Java"
			    name       	"RootPath"
			    value      	"")
			(object Attribute
			    tool       	"Java"
			    name       	"CmIdentification"
			    value      	(value Text ""))
			(object Attribute
			    tool       	"Java"
			    name       	"CopyrightNotice"
			    value      	(value Text "")))
		    quid       	"3E401A5601C2"
		    stereotype 	""
		    language   	"Java")
		(object module "ConnectionPendingException" "NotAModuleType" "NotAModulePart"
		    attributes 	(list Attribute_Set
			(object Attribute
			    tool       	"Java"
			    name       	"FileName"
			    value      	"java\\nio\\channels\\ConnectionPendingException.class")
			(object Attribute
			    tool       	"Java"
			    name       	"RootPath"
			    value      	"")
			(object Attribute
			    tool       	"Java"
			    name       	"CmIdentification"
			    value      	(value Text ""))
			(object Attribute
			    tool       	"Java"
			    name       	"CopyrightNotice"
			    value      	(value Text "")))
		    quid       	"3E401A57019B"
		    stereotype 	""
		    language   	"Java")
		(object module "ClosedByInterruptException" "NotAModuleType" "NotAModulePart"
		    attributes 	(list Attribute_Set
			(object Attribute
			    tool       	"Java"
			    name       	"FileName"
			    value      	"java\\nio\\channels\\ClosedByInterruptException.class")
			(object Attribute
			    tool       	"Java"
			    name       	"RootPath"
			    value      	"")
			(object Attribute
			    tool       	"Java"
			    name       	"CmIdentification"
			    value      	(value Text ""))
			(object Attribute
			    tool       	"Java"
			    name       	"CopyrightNotice"
			    value      	(value Text "")))
		    quid       	"3E401A5B03D2"
		    stereotype 	""
		    language   	"Java")
		(object module "UnresolvedAddressException" "NotAModuleType" "NotAModulePart"
		    attributes 	(list Attribute_Set
			(object Attribute
			    tool       	"Java"
			    name       	"FileName"
			    value      	"java\\nio\\channels\\UnresolvedAddressException.class")
			(object Attribute
			    tool       	"Java"
			    name       	"RootPath"
			    value      	"")
			(object Attribute
			    tool       	"Java"
			    name       	"CmIdentification"
			    value      	(value Text ""))
			(object Attribute
			    tool       	"Java"
			    name       	"CopyrightNotice"
			    value      	(value Text "")))
		    quid       	"3E401A5C02A7"
		    stereotype 	""
		    language   	"Java")
		(object module "NonReadableChannelException" "NotAModuleType" "NotAModulePart"
		    attributes 	(list Attribute_Set
			(object Attribute
			    tool       	"Java"
			    name       	"FileName"
			    value      	"java\\nio\\channels\\NonReadableChannelException.class")
			(object Attribute
			    tool       	"Java"
			    name       	"RootPath"
			    value      	"")
			(object Attribute
			    tool       	"Java"
			    name       	"CmIdentification"
			    value      	(value Text ""))
			(object Attribute
			    tool       	"Java"
			    name       	"CopyrightNotice"
			    value      	(value Text "")))
		    quid       	"3E401B6C003B"
		    stereotype 	""
		    language   	"Java")
		(object module "NonWritableChannelException" "NotAModuleType" "NotAModulePart"
		    attributes 	(list Attribute_Set
			(object Attribute
			    tool       	"Java"
			    name       	"FileName"
			    value      	"java\\nio\\channels\\NonWritableChannelException.class")
			(object Attribute
			    tool       	"Java"
			    name       	"RootPath"
			    value      	"")
			(object Attribute
			    tool       	"Java"
			    name       	"CmIdentification"
			    value      	(value Text ""))
			(object Attribute
			    tool       	"Java"
			    name       	"CopyrightNotice"
			    value      	(value Text "")))
		    quid       	"3E401B700308"
		    stereotype 	""
		    language   	"Java")
		(object module "IllegalBlockingModeException" "NotAModuleType" "NotAModulePart"
		    attributes 	(list Attribute_Set
			(object Attribute
			    tool       	"Java"
			    name       	"FileName"
			    value      	"java\\nio\\channels\\IllegalBlockingModeException.class")
			(object Attribute
			    tool       	"Java"
			    name       	"RootPath"
			    value      	"")
			(object Attribute
			    tool       	"Java"
			    name       	"CmIdentification"
			    value      	(value Text ""))
			(object Attribute
			    tool       	"Java"
			    name       	"CopyrightNotice"
			    value      	(value Text "")))
		    quid       	"3E401BED0073"
		    stereotype 	""
		    language   	"Java")
		(object module "NoConnectionPendingException" "NotAModuleType" "NotAModulePart"
		    attributes 	(list Attribute_Set
			(object Attribute
			    tool       	"Java"
			    name       	"FileName"
			    value      	"java\\nio\\channels\\NoConnectionPendingException.class")
			(object Attribute
			    tool       	"Java"
			    name       	"RootPath"
			    value      	"")
			(object Attribute
			    tool       	"Java"
			    name       	"CmIdentification"
			    value      	(value Text ""))
			(object Attribute
			    tool       	"Java"
			    name       	"CopyrightNotice"
			    value      	(value Text "")))
		    quid       	"3E401BF200E8"
		    stereotype 	""
		    language   	"Java")
		(object module "FileLockInterruptionException" "NotAModuleType" "NotAModulePart"
		    attributes 	(list Attribute_Set
			(object Attribute
			    tool       	"Java"
			    name       	"FileName"
			    value      	"java\\nio\\channels\\FileLockInterruptionException.class")
			(object Attribute
			    tool       	"Java"
			    name       	"RootPath"
			    value      	"")
			(object Attribute
			    tool       	"Java"
			    name       	"CmIdentification"
			    value      	(value Text ""))
			(object Attribute
			    tool       	"Java"
			    name       	"CopyrightNotice"
			    value      	(value Text "")))
		    quid       	"3E401C6B020E"
		    stereotype 	""
		    language   	"Java")
		(object module "UnsupportedAddressTypeException" "NotAModuleType" "NotAModulePart"
		    attributes 	(list Attribute_Set
			(object Attribute
			    tool       	"Java"
			    name       	"FileName"
			    value      	"java\\nio\\channels\\UnsupportedAddressTypeException.class")
			(object Attribute
			    tool       	"Java"
			    name       	"RootPath"
			    value      	"")
			(object Attribute
			    tool       	"Java"
			    name       	"CmIdentification"
			    value      	(value Text ""))
			(object Attribute
			    tool       	"Java"
			    name       	"CopyrightNotice"
			    value      	(value Text "")))
		    quid       	"3E401CF2001E"
		    stereotype 	""
		    language   	"Java")
		(object module "Channels$ReadableByteChannelImpl" "NotAModuleType" "NotAModulePart"
		    attributes 	(list Attribute_Set
			(object Attribute
			    tool       	"Java"
			    name       	"FileName"
			    value      	"java\\nio\\channels\\Channels$ReadableByteChannelImpl.class")
			(object Attribute
			    tool       	"Java"
			    name       	"RootPath"
			    value      	"")
			(object Attribute
			    tool       	"Java"
			    name       	"CmIdentification"
			    value      	(value Text ""))
			(object Attribute
			    tool       	"Java"
			    name       	"CopyrightNotice"
			    value      	(value Text "")))
		    quid       	"3E401D9D002E"
		    stereotype 	""
		    visible_modules 	(list dependency_list
			(object Module_Visibility_Relationship
			    quid       	"3E401D9D0165"
			    supplier   	"Component View::java::io::InputStream"
			    quidu      	"3E400BBD0256"
			    supplier_is_spec 	TRUE))
		    language   	"Java")
		(object module "Channels$WritableByteChannelImpl" "NotAModuleType" "NotAModulePart"
		    attributes 	(list Attribute_Set
			(object Attribute
			    tool       	"Java"
			    name       	"FileName"
			    value      	"java\\nio\\channels\\Channels$WritableByteChannelImpl.class")
			(object Attribute
			    tool       	"Java"
			    name       	"RootPath"
			    value      	"")
			(object Attribute
			    tool       	"Java"
			    name       	"CmIdentification"
			    value      	(value Text ""))
			(object Attribute
			    tool       	"Java"
			    name       	"CopyrightNotice"
			    value      	(value Text "")))
		    quid       	"3E401DAC022E"
		    stereotype 	""
		    visible_modules 	(list dependency_list
			(object Module_Visibility_Relationship
			    quid       	"3E401DAC035B"
			    supplier   	"Component View::java::io::OutputStream"
			    quidu      	"3E400BC60126"
			    supplier_is_spec 	TRUE))
		    language   	"Java")
		(object SubSystem "spi"
		    quid       	"3E400C6C0347"
		    visible_modules 	(list dependency_list
			(object Module_Visibility_Relationship
			    quid       	"3E4016D9004B"
			    supplier   	"Component View::java::lang"
			    quidu      	"3E400BBB015B"
			    supplier_is_subsystem 	TRUE)
			(object Module_Visibility_Relationship
			    quid       	"3E4016DE0049"
			    supplier   	"Component View::java::util"
			    quidu      	"3E400BC001EB"
			    supplier_is_subsystem 	TRUE)
			(object Module_Visibility_Relationship
			    quid       	"3E4016DE005D"
			    supplier   	"::nio::ch"
			    quidu      	"3E400BCD032B"
			    supplier_is_subsystem 	TRUE)
			(object Module_Visibility_Relationship
			    quid       	"3E401C710362"
			    supplier   	"Component View::java::nio::channels"
			    quidu      	"3E400BE30369"
			    supplier_is_subsystem 	TRUE)
			(object Module_Visibility_Relationship
			    quid       	"3E401D750117"
			    supplier   	"Component View::java::lang::reflect"
			    quidu      	"3E400BE002B9"
			    supplier_is_subsystem 	TRUE))
		    physical_models 	(list unit_reference_list
			(object module "SelectorProvider" "NotAModuleType" "NotAModulePart"
			    attributes 	(list Attribute_Set
				(object Attribute
				    tool       	"Java"
				    name       	"FileName"
				    value      	"java\\nio\\channels\\spi\\SelectorProvider.class")
				(object Attribute
				    tool       	"Java"
				    name       	"RootPath"
				    value      	"")
				(object Attribute
				    tool       	"Java"
				    name       	"CmIdentification"
				    value      	(value Text ""))
				(object Attribute
				    tool       	"Java"
				    name       	"CopyrightNotice"
				    value      	(value Text "")))
			    quid       	"3E400C6C0348"
			    stereotype 	""
			    visible_modules 	(list dependency_list
				(object Module_Visibility_Relationship
				    quid       	"3E4016D9004C"
				    supplier   	"Component View::java::lang::Class"
				    quidu      	"3E400BBB0176"
				    supplier_is_spec 	TRUE))
			    language   	"Java")
			(object module "AbstractSelector" "NotAModuleType" "NotAModulePart"
			    attributes 	(list Attribute_Set
				(object Attribute
				    tool       	"Java"
				    name       	"FileName"
				    value      	"java\\nio\\channels\\spi\\AbstractSelector.class")
				(object Attribute
				    tool       	"Java"
				    name       	"RootPath"
				    value      	"")
				(object Attribute
				    tool       	"Java"
				    name       	"CmIdentification"
				    value      	(value Text ""))
				(object Attribute
				    tool       	"Java"
				    name       	"CopyrightNotice"
				    value      	(value Text "")))
			    quid       	"3E400D5F016F"
			    stereotype 	""
			    visible_modules 	(list dependency_list
				(object Module_Visibility_Relationship
				    quid       	"3E4016DE0035"
				    supplier   	"Component View::java::nio::channels::spi::SelectorProvider"
				    quidu      	"3E400C6C0348"
				    supplier_is_spec 	TRUE)
				(object Module_Visibility_Relationship
				    quid       	"3E4016DE004A"
				    supplier   	"Component View::java::util::Set"
				    quidu      	"3E400BC101C4"
				    supplier_is_spec 	TRUE))
			    language   	"Java")
			(object module "AbstractSelectableChannel" "NotAModuleType" "NotAModulePart"
			    attributes 	(list Attribute_Set
				(object Attribute
				    tool       	"Java"
				    name       	"FileName"
				    value      	"java\\nio\\channels\\spi\\AbstractSelectableChannel.class")
				(object Attribute
				    tool       	"Java"
				    name       	"RootPath"
				    value      	"")
				(object Attribute
				    tool       	"Java"
				    name       	"CmIdentification"
				    value      	(value Text ""))
				(object Attribute
				    tool       	"Java"
				    name       	"CopyrightNotice"
				    value      	(value Text "")))
			    quid       	"3E400D5F0260"
			    stereotype 	""
			    visible_modules 	(list dependency_list
				(object Module_Visibility_Relationship
				    quid       	"3E401C710344"
				    supplier   	"Component View::java::nio::channels::spi::SelectorProvider"
				    quidu      	"3E400C6C0348"
				    supplier_is_spec 	TRUE)
				(object Module_Visibility_Relationship
				    quid       	"3E401C71036C"
				    supplier   	"Component View::java::nio::channels::SelectionKey"
				    quidu      	"3E400D5F0256"
				    supplier_is_spec 	TRUE)
				(object Module_Visibility_Relationship
				    quid       	"3E401C71038A"
				    supplier   	"Component View::java::lang::Class"
				    quidu      	"3E400BBB0176"
				    supplier_is_spec 	TRUE))
			    language   	"Java")
			(object module "AbstractSelectionKey" "NotAModuleType" "NotAModulePart"
			    attributes 	(list Attribute_Set
				(object Attribute
				    tool       	"Java"
				    name       	"FileName"
				    value      	"java\\nio\\channels\\spi\\AbstractSelectionKey.class")
				(object Attribute
				    tool       	"Java"
				    name       	"RootPath"
				    value      	"")
				(object Attribute
				    tool       	"Java"
				    name       	"CmIdentification"
				    value      	(value Text ""))
				(object Attribute
				    tool       	"Java"
				    name       	"CopyrightNotice"
				    value      	(value Text "")))
			    quid       	"3E400F3D027B"
			    stereotype 	""
			    language   	"Java")
			(object module "AbstractInterruptibleChannel" "NotAModuleType" "NotAModulePart"
			    attributes 	(list Attribute_Set
				(object Attribute
				    tool       	"Java"
				    name       	"FileName"
				    value      	"java\\nio\\channels\\spi\\AbstractInterruptibleChannel.class")
				(object Attribute
				    tool       	"Java"
				    name       	"RootPath"
				    value      	"")
				(object Attribute
				    tool       	"Java"
				    name       	"CmIdentification"
				    value      	(value Text ""))
				(object Attribute
				    tool       	"Java"
				    name       	"CopyrightNotice"
				    value      	(value Text "")))
			    quid       	"3E40107A01F5"
			    stereotype 	""
			    visible_modules 	(list dependency_list
				(object Module_Visibility_Relationship
				    quid       	"3E401D750121"
				    supplier   	"Component View::java::lang::reflect::Method"
				    quidu      	"3E400BE1015D"
				    supplier_is_spec 	TRUE)
				(object Module_Visibility_Relationship
				    quid       	"3E401D750135"
				    supplier   	"Component View::java::lang::Class"
				    quidu      	"3E400BBB0176"
				    supplier_is_spec 	TRUE))
			    language   	"Java")
			(object module "AbstractInterruptibleChannel$FooChannel" "NotAModuleType" "NotAModulePart"
			    attributes 	(list Attribute_Set
				(object Attribute
				    tool       	"Java"
				    name       	"FileName"
				    value      	"java\\nio\\channels\\spi\\AbstractInterruptibleChannel$FooChannel.class")
				(object Attribute
				    tool       	"Java"
				    name       	"RootPath"
				    value      	"")
				(object Attribute
				    tool       	"Java"
				    name       	"CmIdentification"
				    value      	(value Text ""))
				(object Attribute
				    tool       	"Java"
				    name       	"CopyrightNotice"
				    value      	(value Text "")))
			    quid       	"3E4020A7039E"
			    stereotype 	""
			    language   	"Java"))
		    physical_presentations 	(list unit_reference_list)))
	    physical_presentations 	(list unit_reference_list))
	(object SubSystem "charset"
	    quid       	"3E400BF2035A"
	    visible_modules 	(list dependency_list
		(object Module_Visibility_Relationship
		    quid       	"3E400D9B01BC"
		    supplier   	"Component View::java::nio::charset::spi"
		    quidu      	"3E400D9A0373"
		    supplier_is_subsystem 	TRUE)
		(object Module_Visibility_Relationship
		    quid       	"3E400D9B01C6"
		    supplier   	"Component View::java::lang"
		    quidu      	"3E400BBB015B"
		    supplier_is_subsystem 	TRUE)
		(object Module_Visibility_Relationship
		    quid       	"3E400D9B01C8"
		    supplier   	"Component View::java::util"
		    quidu      	"3E400BC001EB"
		    supplier_is_subsystem 	TRUE)
		(object Module_Visibility_Relationship
		    quid       	"3E4011700267"
		    supplier   	"Component View::java::lang::ref"
		    quidu      	"3E400BBC0054"
		    supplier_is_subsystem 	TRUE))
	    physical_models 	(list unit_reference_list
		(object module "Charset" "NotAModuleType" "NotAModulePart"
		    attributes 	(list Attribute_Set
			(object Attribute
			    tool       	"Java"
			    name       	"FileName"
			    value      	"java\\nio\\charset\\Charset.class")
			(object Attribute
			    tool       	"Java"
			    name       	"RootPath"
			    value      	"")
			(object Attribute
			    tool       	"Java"
			    name       	"CmIdentification"
			    value      	(value Text ""))
			(object Attribute
			    tool       	"Java"
			    name       	"CopyrightNotice"
			    value      	(value Text "")))
		    quid       	"3E400BF2035B"
		    stereotype 	""
		    visible_modules 	(list dependency_list
			(object Module_Visibility_Relationship
			    quid       	"3E400D9B01BD"
			    supplier   	"Component View::java::nio::charset::spi::CharsetProvider"
			    quidu      	"3E400D9A0374"
			    supplier_is_spec 	TRUE)
			(object Module_Visibility_Relationship
			    quid       	"3E400D9B01C7"
			    supplier   	"Component View::java::lang::ThreadLocal"
			    quidu      	"3E400BE403E6"
			    supplier_is_spec 	TRUE)
			(object Module_Visibility_Relationship
			    quid       	"3E400D9B01C9"
			    supplier   	"Component View::java::util::Set"
			    quidu      	"3E400BC101C4"
			    supplier_is_spec 	TRUE)
			(object Module_Visibility_Relationship
			    quid       	"3E400D9B01D0"
			    supplier   	"Component View::java::lang::Class"
			    quidu      	"3E400BBB0176"
			    supplier_is_spec 	TRUE))
		    language   	"Java")
		(object module "CharsetDecoder" "NotAModuleType" "NotAModulePart"
		    attributes 	(list Attribute_Set
			(object Attribute
			    tool       	"Java"
			    name       	"FileName"
			    value      	"java\\nio\\charset\\CharsetDecoder.class")
			(object Attribute
			    tool       	"Java"
			    name       	"RootPath"
			    value      	"")
			(object Attribute
			    tool       	"Java"
			    name       	"CmIdentification"
			    value      	(value Text ""))
			(object Attribute
			    tool       	"Java"
			    name       	"CopyrightNotice"
			    value      	(value Text "")))
		    quid       	"3E400BF203A5"
		    stereotype 	""
		    visible_modules 	(list dependency_list
			(object Module_Visibility_Relationship
			    quid       	"3E40116700DD"
			    supplier   	"Component View::java::nio::charset::Charset"
			    quidu      	"3E400BF2035B"
			    supplier_is_spec 	TRUE)
			(object Module_Visibility_Relationship
			    quid       	"3E40116700F1"
			    supplier   	"Component View::java::nio::charset::CodingErrorAction"
			    quidu      	"3E40116600C8"
			    supplier_is_spec 	TRUE)
			(object Module_Visibility_Relationship
			    quid       	"3E4011670105"
			    supplier   	"Component View::java::lang::Class"
			    quidu      	"3E400BBB0176"
			    supplier_is_spec 	TRUE))
		    language   	"Java")
		(object module "CharsetEncoder" "NotAModuleType" "NotAModulePart"
		    attributes 	(list Attribute_Set
			(object Attribute
			    tool       	"Java"
			    name       	"FileName"
			    value      	"java\\nio\\charset\\CharsetEncoder.class")
			(object Attribute
			    tool       	"Java"
			    name       	"RootPath"
			    value      	"")
			(object Attribute
			    tool       	"Java"
			    name       	"CmIdentification"
			    value      	(value Text ""))
			(object Attribute
			    tool       	"Java"
			    name       	"CopyrightNotice"
			    value      	(value Text "")))
		    quid       	"3E400BF203AB"
		    stereotype 	""
		    visible_modules 	(list dependency_list
			(object Module_Visibility_Relationship
			    quid       	"3E401170023F"
			    supplier   	"Component View::java::nio::charset::Charset"
			    quidu      	"3E400BF2035B"
			    supplier_is_spec 	TRUE)
			(object Module_Visibility_Relationship
			    quid       	"3E4011700253"
			    supplier   	"Component View::java::nio::charset::CodingErrorAction"
			    quidu      	"3E40116600C8"
			    supplier_is_spec 	TRUE)
			(object Module_Visibility_Relationship
			    quid       	"3E4011700268"
			    supplier   	"Component View::java::lang::ref::WeakReference"
			    quidu      	"3E400BD001F9"
			    supplier_is_spec 	TRUE)
			(object Module_Visibility_Relationship
			    quid       	"3E401170027B"
			    supplier   	"Component View::java::lang::Class"
			    quidu      	"3E400BBB0176"
			    supplier_is_spec 	TRUE))
		    language   	"Java")
		(object module "CoderResult" "NotAModuleType" "NotAModulePart"
		    attributes 	(list Attribute_Set
			(object Attribute
			    tool       	"Java"
			    name       	"FileName"
			    value      	"java\\nio\\charset\\CoderResult.class")
			(object Attribute
			    tool       	"Java"
			    name       	"RootPath"
			    value      	"")
			(object Attribute
			    tool       	"Java"
			    name       	"CmIdentification"
			    value      	(value Text ""))
			(object Attribute
			    tool       	"Java"
			    name       	"CopyrightNotice"
			    value      	(value Text "")))
		    quid       	"3E400DA5033D"
		    stereotype 	""
		    visible_modules 	(list dependency_list
			(object Module_Visibility_Relationship
			    quid       	"3E400F9901BF"
			    supplier   	"Component View::java::nio::charset::CoderResult$Cache"
			    quidu      	"3E400F9901A1"
			    supplier_is_spec 	TRUE)
			(object Module_Visibility_Relationship
			    quid       	"3E400F9901D3"
			    supplier   	"Component View::java::lang::Class"
			    quidu      	"3E400BBB0176"
			    supplier_is_spec 	TRUE))
		    language   	"Java")
		(object module "CharacterCodingException" "NotAModuleType" "NotAModulePart"
		    attributes 	(list Attribute_Set
			(object Attribute
			    tool       	"Java"
			    name       	"FileName"
			    value      	"java\\nio\\charset\\CharacterCodingException.class")
			(object Attribute
			    tool       	"Java"
			    name       	"RootPath"
			    value      	"")
			(object Attribute
			    tool       	"Java"
			    name       	"CmIdentification"
			    value      	(value Text ""))
			(object Attribute
			    tool       	"Java"
			    name       	"CopyrightNotice"
			    value      	(value Text "")))
		    quid       	"3E400F990165"
		    stereotype 	""
		    language   	"Java")
		(object module "CoderResult$Cache" "NotAModuleType" "NotAModulePart"
		    attributes 	(list Attribute_Set
			(object Attribute
			    tool       	"Java"
			    name       	"FileName"
			    value      	"java\\nio\\charset\\CoderResult$Cache.class")
			(object Attribute
			    tool       	"Java"
			    name       	"RootPath"
			    value      	"")
			(object Attribute
			    tool       	"Java"
			    name       	"CmIdentification"
			    value      	(value Text ""))
			(object Attribute
			    tool       	"Java"
			    name       	"CopyrightNotice"
			    value      	(value Text "")))
		    quid       	"3E400F9901A1"
		    stereotype 	""
		    visible_modules 	(list dependency_list
			(object Module_Visibility_Relationship
			    quid       	"3E40138D019C"
			    supplier   	"Component View::java::util::Map"
			    quidu      	"3E400BC001EC"
			    supplier_is_spec 	TRUE))
		    language   	"Java")
		(object module "CodingErrorAction" "NotAModuleType" "NotAModulePart"
		    attributes 	(list Attribute_Set
			(object Attribute
			    tool       	"Java"
			    name       	"FileName"
			    value      	"java\\nio\\charset\\CodingErrorAction.class")
			(object Attribute
			    tool       	"Java"
			    name       	"RootPath"
			    value      	"")
			(object Attribute
			    tool       	"Java"
			    name       	"CmIdentification"
			    value      	(value Text ""))
			(object Attribute
			    tool       	"Java"
			    name       	"CopyrightNotice"
			    value      	(value Text "")))
		    quid       	"3E40116600C8"
		    stereotype 	""
		    language   	"Java")
		(object module "CoderMalfunctionError" "NotAModuleType" "NotAModulePart"
		    attributes 	(list Attribute_Set
			(object Attribute
			    tool       	"Java"
			    name       	"FileName"
			    value      	"java\\nio\\charset\\CoderMalfunctionError.class")
			(object Attribute
			    tool       	"Java"
			    name       	"RootPath"
			    value      	"")
			(object Attribute
			    tool       	"Java"
			    name       	"CmIdentification"
			    value      	(value Text ""))
			(object Attribute
			    tool       	"Java"
			    name       	"CopyrightNotice"
			    value      	(value Text "")))
		    quid       	"3E4016DB036F"
		    stereotype 	""
		    language   	"Java")
		(object module "MalformedInputException" "NotAModuleType" "NotAModulePart"
		    attributes 	(list Attribute_Set
			(object Attribute
			    tool       	"Java"
			    name       	"FileName"
			    value      	"java\\nio\\charset\\MalformedInputException.class")
			(object Attribute
			    tool       	"Java"
			    name       	"RootPath"
			    value      	"")
			(object Attribute
			    tool       	"Java"
			    name       	"CmIdentification"
			    value      	(value Text ""))
			(object Attribute
			    tool       	"Java"
			    name       	"CopyrightNotice"
			    value      	(value Text "")))
		    quid       	"3E4018170161"
		    stereotype 	""
		    language   	"Java")
		(object module "UnsupportedCharsetException" "NotAModuleType" "NotAModulePart"
		    attributes 	(list Attribute_Set
			(object Attribute
			    tool       	"Java"
			    name       	"FileName"
			    value      	"java\\nio\\charset\\UnsupportedCharsetException.class")
			(object Attribute
			    tool       	"Java"
			    name       	"RootPath"
			    value      	"")
			(object Attribute
			    tool       	"Java"
			    name       	"CmIdentification"
			    value      	(value Text ""))
			(object Attribute
			    tool       	"Java"
			    name       	"CopyrightNotice"
			    value      	(value Text "")))
		    quid       	"3E401A720353"
		    stereotype 	""
		    language   	"Java")
		(object module "IllegalCharsetNameException" "NotAModuleType" "NotAModulePart"
		    attributes 	(list Attribute_Set
			(object Attribute
			    tool       	"Java"
			    name       	"FileName"
			    value      	"java\\nio\\charset\\IllegalCharsetNameException.class")
			(object Attribute
			    tool       	"Java"
			    name       	"RootPath"
			    value      	"")
			(object Attribute
			    tool       	"Java"
			    name       	"CmIdentification"
			    value      	(value Text ""))
			(object Attribute
			    tool       	"Java"
			    name       	"CopyrightNotice"
			    value      	(value Text "")))
		    quid       	"3E401A730264"
		    stereotype 	""
		    language   	"Java")
		(object module "UnmappableCharacterException" "NotAModuleType" "NotAModulePart"
		    attributes 	(list Attribute_Set
			(object Attribute
			    tool       	"Java"
			    name       	"FileName"
			    value      	"java\\nio\\charset\\UnmappableCharacterException.class")
			(object Attribute
			    tool       	"Java"
			    name       	"RootPath"
			    value      	"")
			(object Attribute
			    tool       	"Java"
			    name       	"CmIdentification"
			    value      	(value Text ""))
			(object Attribute
			    tool       	"Java"
			    name       	"CopyrightNotice"
			    value      	(value Text "")))
		    quid       	"3E401B700254"
		    stereotype 	""
		    language   	"Java")
		(object SubSystem "spi"
		    quid       	"3E400D9A0373"
		    physical_models 	(list unit_reference_list
			(object module "CharsetProvider" "NotAModuleType" "NotAModulePart"
			    attributes 	(list Attribute_Set
				(object Attribute
				    tool       	"Java"
				    name       	"FileName"
				    value      	"java\\nio\\charset\\spi\\CharsetProvider.class")
				(object Attribute
				    tool       	"Java"
				    name       	"RootPath"
				    value      	"")
				(object Attribute
				    tool       	"Java"
				    name       	"CmIdentification"
				    value      	(value Text ""))
				(object Attribute
				    tool       	"Java"
				    name       	"CopyrightNotice"
				    value      	(value Text "")))
			    quid       	"3E400D9A0374"
			    stereotype 	""
			    language   	"Java"))
		    physical_presentations 	(list unit_reference_list)))
	    physical_presentations 	(list unit_reference_list)))
    physical_presentations 	(list unit_reference_list))
