#
# NAME
#	  $RCSfile: Makefile,v $
# DESCRIPTION
#	  [given below in javadoc format]
# DELTA
#	  $Revision: 1.9 $
# CREATED
#	  $Date: 2002/10/22 16:23:36 $
# COPYRIGHT
#	  Westhawk Ltd
# TO DO
#


DISTRIBDIR=$(TOPDISTRIBDIR)/uk/co/westhawk/snmp/beans

SRC=\
	SNMPBean.java \
	SNMPRunBean.java \
	DialogChannelStatusBean.java \
	AnnexModemStatusBean.java \
	NcdPerfDataBean.java \
	AscendActiveSessionBean.java \
	IsHostReachableBean.java \
	InterfaceIndexesBean.java \
	NTPrintQBean.java \
	NTServiceNamesBean.java \
	NTSharedResBean.java \
	NTUserNamesBean.java \
	OneInterfaceBean.java \
	OneNTPrintQBean.java \
	OneNTServiceBean.java \
	OneNTSharedResBean.java \
	UsmDiscoveryBean.java 

TOJAR=\
	$(OBJ) 

TOORACLEJAR=UsmDiscoveryBean.class

TOZIP= \
	$(SRC) \
	Makefile

include ../../../../../Makefile.general


