#
# NAME
#	  $RCSfile: Makefile,v $
# DESCRIPTION
#	  [given below in javadoc format]
# DELTA
#	  $Revision: 3.10 $
# CREATED
#	  $Date: 2002/10/22 16:24:14 $
# COPYRIGHT
#	  Westhawk Ltd
# TO DO
#


DISTRIBDIR=$(TOPDISTRIBDIR)/uk/co/westhawk/snmp/pdu

SRC=\
	BlockPdu.java \
	DiscoveryPdu.java \
	GetNextPdu_vec.java \
	GetPdu_vec.java \
	InformPdu_vec.java \
	InterfaceGetNextPdu.java \
	InterfacePdu.java \
	InterfacesPdu.java \
	OneGetBulkPdu.java \
	OneGetNextPdu.java \
	OneGetPdu.java \
	OneInformPdu.java \
	OneIntPdu.java \
	OneSetPdu.java \
	OneTrapPduv1.java \
	OneTrapPduv2.java \
	SetPdu_vec.java \
	UpSincePdu.java \
	PassiveTrapPduv1.java \
	PassiveTrapPduv2.java

TOJAR=\
	$(OBJ) 

TOZIP= \
	$(SRC) \
	Makefile

TOORACLEJAR=\
	DiscoveryPdu.class \
	OneTrapPduv1.class \
	OneTrapPduv2.class \
	PassiveTrapPduv1.class \
	PassiveTrapPduv2.class

include ../../../../../Makefile.general

