/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_cisco_eManager_eManager_processSequencer_common_IOUtil */

#ifndef _Included_com_cisco_eManager_eManager_processSequencer_common_IOUtil
#define _Included_com_cisco_eManager_eManager_processSequencer_common_IOUtil
#ifdef __cplusplus
extern "C" {
#endif
/* Inaccessible static: msInstance */
#undef com_cisco_eManager_eManager_processSequencer_common_IOUtil_INIT
#define com_cisco_eManager_eManager_processSequencer_common_IOUtil_INIT 0L
#undef com_cisco_eManager_eManager_processSequencer_common_IOUtil_FILE
#define com_cisco_eManager_eManager_processSequencer_common_IOUtil_FILE 1L
#undef com_cisco_eManager_eManager_processSequencer_common_IOUtil_DEV_NULL
#define com_cisco_eManager_eManager_processSequencer_common_IOUtil_DEV_NULL 2L
#undef com_cisco_eManager_eManager_processSequencer_common_IOUtil_REINIT_OP
#define com_cisco_eManager_eManager_processSequencer_common_IOUtil_REINIT_OP 100L
#undef com_cisco_eManager_eManager_processSequencer_common_IOUtil_TOGGLE_OP
#define com_cisco_eManager_eManager_processSequencer_common_IOUtil_TOGGLE_OP 200L
/*
 * Class:     com_cisco_eManager_eManager_processSequencer_common_IOUtil
 * Method:    RedirectIO
 * Signature: (Ljava/lang/String;I)I
 */
JNIEXPORT jint JNICALL Java_com_cisco_eManager_eManager_processSequencer_common_IOUtil_RedirectIO
  (JNIEnv *, jobject, jstring, jint);

#ifdef __cplusplus
}
#endif
#endif
