#
# NAME
#      $RCSfile: Makefile,v $
# DESCRIPTION
#      [given below in javadoc format]
# DELTA
#      $Revision: 1.4 $
# CREATED
#      $Date: 2002/11/06 12:52:40 $
# COPYRIGHT
#      Westhawk Ltd
# TO DO
#

DISTRIBDIR=$(TOPDISTRIBDIR)/uk/co/westhawk/examplev1

SRC=\
	propertyDialog.java \
	Util.java \
	BigBlockOperation.java \
	InterfaceSpeed.java \
	Interfaces.java \
	OneBlockOperation.java \
	OneInterface.java \
	OneNTPrintQ.java \
	OneNTService.java \
	OneNTSharedRes.java \
	ReceiveTrap.java \
	SendTrap.java \
	UpSince.java \
	getAllInterfaces.java \
	getAllInterfacesUI.java \
	get_next.java \
	get_one.java \
	set_one.java \
	testAscendActiveSessionBean.java \
	testDialogChannelStatusBean.java \
	testInterfaceBean.java \
	testNTPrintQBean.java \
	testNTServiceNamesBean.java \
	testNTSharedResBean.java \
	testNTUserNamesBean.java \
	testNcdPerfDataBean.java \
	test_threads.java \
	MultipleHosts.java


PROP=\
	BigBlockOperation.properties \
	InterfaceSpeed.properties \
	Interfaces.properties \
	OneBlockOperation.properties \
	ReceiveTrap.properties \
	SendTrap.properties \
	UpSince.properties \
	getAllInterfaces.properties \
	getAllInterfacesUI.properties \
	get_next.properties \
	setSnmpEnableAuthenTraps.properties \
	get_one.properties \
	set_one.properties \
	set_one_wrong.properties \
	testDialogChannelStatusBean.properties \
	testNcdPerfDataBean.properties \
	test_threads.properties \
	MultipleHosts.properties

SCRIPT=\
	runapplication.bat \
	setenv.bat \
	runapplication.sh \
	setenv.sh

TOJAR=\
	$(OBJ)

TOORACLEJAR=

TOZIP= \
	$(SRC) \
	$(PROP) \
	$(SCRIPT) \
	Makefile 

include ../../../../Makefile.general


