<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions targetNamespace="http://event.soap.eManager.cisco.com" xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:apachesoap="http://xml.apache.org/xml-soap" xmlns:impl="http://event.soap.eManager.cisco.com" xmlns:intf="http://event.soap.eManager.cisco.com" xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:wsdlsoap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:xsd="http://www.w3.org/2001/XMLSchema">

   <wsdl:message name="xmlMessageRequest">

      <wsdl:part name="in0" type="soapenc:string"/>

      <wsdl:part name="in1" type="soapenc:string"/>

   </wsdl:message>

   <wsdl:message name="xmlMessageResponse">

      <wsdl:part name="xmlMessageReturn" type="soapenc:string"/>

   </wsdl:message>

   <wsdl:portType name="EventManager">

      <wsdl:operation name="xmlMessage" parameterOrder="in0 in1">

         <wsdl:input message="impl:xmlMessageRequest" name="xmlMessageRequest"/>

         <wsdl:output message="impl:xmlMessageResponse" name="xmlMessageResponse"/>

      </wsdl:operation>

   </wsdl:portType>

   <wsdl:binding name="EventManagerSoapBinding" type="impl:EventManager">

      <wsdlsoap:binding style="rpc" transport="http://schemas.xmlsoap.org/soap/http"/>

      <wsdl:operation name="xmlMessage">

         <wsdlsoap:operation soapAction="xmlMessage"/>

         <wsdl:input name="xmlMessageRequest">

            <wsdlsoap:body encodingStyle="http://schemas.xmlsoap.org/soap/encoding/" namespace="http://event.soap.eManager.cisco.com" use="encoded"/>

         </wsdl:input>

         <wsdl:output name="xmlMessageResponse">

            <wsdlsoap:body encodingStyle="http://schemas.xmlsoap.org/soap/encoding/" namespace="http://event.soap.eManager.cisco.com" use="encoded"/>

         </wsdl:output>

      </wsdl:operation>

   </wsdl:binding>

   <wsdl:service name="EventManagerService">

      <wsdl:port binding="impl:EventManagerSoapBinding" name="EventManager">

         <wsdlsoap:address location="http://localhost:9080/emanager/services/EventManager"/>

      </wsdl:port>

   </wsdl:service>

</wsdl:definitions>
