#
# NAME
#      $RCSfile: Makefile,v $
# DESCRIPTION
#      [given below in javadoc format]
# DELTA
#      $Revision: 1.2 $
# CREATED
#      $Date: 2002/10/15 12:59:32 $
# COPYRIGHT
#      Westhawk Ltd
# TO DO
#

DISTRIBDIR=$(TOPDISTRIBDIR)/org/bouncycastle/crypto/params

SRC=\
	DESParameters.java \
	KeyParameter.java \

HTML=

SCRIPT=

TOJAR=\
	$(OBJ)

TOORACLEJAR=$(TOJAR)

TOZIP= \
	$(SRC) \
	$(HTML) \
	$(SCRIPT) \
	Makefile 

include ../../../../Makefile.general

