#
# NAME
#      $RCSfile: Makefile,v $
# DESCRIPTION
#      [given below in javadoc format]
# DELTA
#      $Revision: 1.7 $
# CREATED
#      $Date: 2002/10/15 12:59:32 $
# COPYRIGHT
#      Westhawk Ltd
# TO DO
#

DISTRIBDIR=$(TOPDISTRIBDIR)/uk/co/westhawk/snmp

SRC=

TOZIP=Makefile
TOJAR= 
TOORACLEJAR=$(TOJAR)

DIRS=\
	stack \
	pdu \
	util \
	net \
	beans \
	event 

ZIPDIRS= $(DIRS)
JARDIRS= $(DIRS)

ORACLEJARDIRS= $(JARDIRS)

include ../../../../Makefile.general
