#
# NAME
#      $RCSfile: Makefile,v $
# DESCRIPTION
#      [given below in javadoc format]
# DELTA
#      $Revision: 1.6 $
# CREATED
#      $Date: 2002/10/22 16:27:22 $
# COPYRIGHT
#      Westhawk Ltd
# TO DO
#

DISTRIBDIR=$(TOPDISTRIBDIR)/uk/co/westhawk/visual

SRC=\
	BareGraph.java \
	Graph.java \
	GraphDataSet.java \
	Level.java \
	LevelDraw.java

SCRIPT=

TOJAR=\
	$(OBJ)

TOORACLEJAR=

#
# Do not distribute BareGraph.java
#
TOZIP= \
	$(SRC) \
	$(SCRIPT) \
	Makefile 

include ../../../../Makefile.general

