#
# NAME
#      $RCSfile: Makefile,v $
# DESCRIPTION
#      [given below in javadoc format]
# DELTA
#      $Revision: 1.2 $
# CREATED
#      $Date: 2002/10/22 16:22:02 $
# COPYRIGHT
#      Westhawk Ltd
# TO DO
#

DISTRIBDIR=$(TOPDISTRIBDIR)/uk/co/westhawk/examplev2c

SRC=\
	get_bulk.java \
	get_next.java \
	set_one.java \
	SendTrap.java \
	ReceiveTrap.java \
	SendInform.java \
	Util.java 

PROP=\
	get_bulk.properties \
	get_next.properties \
	set_one.properties \
	SendTrap.properties \
	ReceiveTrap.properties \
	SendInform.properties

SCRIPT=\
	setenv.bat \
	runapplication.bat \
	setenv.sh \
	runapplication.sh 

TOJAR=\
	$(OBJ)

TOORACLEJAR=

TOZIP= \
	$(SRC) \
	$(PROP) \
	$(SCRIPT) \
	Makefile 

include ../../../../Makefile.general

