#
# NAME
#      $RCSfile: Makefile,v $
# DESCRIPTION
#      [given below in javadoc format]
# DELTA
#      $Revision: 1.3 $
# CREATED
#      $Date: 2002/10/15 12:59:30 $
# COPYRIGHT
#      Westhawk Ltd
# TO DO
#

DISTRIBDIR=$(TOPDISTRIBDIR)/javadoc

SRC= 
TOJAR= 
TOORACLEJAR= 

TOZIP= \

include ../Makefile.general

