#
# NAME
#      $RCSfile: Makefile,v $
# DESCRIPTION
#      [given below in javadoc format]
# DELTA
#      $Revision: 1.13 $
# CREATED
#      $Date: 2002/10/22 16:16:38 $
# COPYRIGHT
#      Westhawk Ltd
# TO DO
#

DISTRIBDIR=$(TOPDISTRIBDIR)/uk/co/westhawk

SRC=

TOZIP=Makefile
TOJAR= 
TOORACLEJAR=$(TOJAR)

DIRS=\
	examplev3 \
	examplev2c \
	examplev1 \
	nothread \
	snmp \
	visual \
	servlet \
	test

ZIPDIRS= $(DIRS)

JARDIRS=\
	snmp \
	visual

ORACLEJARDIRS=\
	snmp \
	nothread

include ../../../Makefile.general


